### ISSUE TITLE
Using recent files in repo outside of Composer

### ISSUE THREAD

**Issue by nitsuj102284** [cartalyst/stripe#100]
I updated Cartalyst/Stripe to the latest version via Composer
`"cartalyst/stripe-laravel": "8.0.*",`

However, it does not include the latest files in the repo, and I'm not sure what is best practice for getting the latest files not downloaded thru Composer.

For instance, I downloaded **Api/Sources.php** from the repo and backed up the file that was downloaded via Composer, so that I can make use of **Stripe::sources()->all()**. Is this recommended? I am concerned about future composer update overriding the file and breaking my app.

How should I proceed?

**Comment by brunogaspar** [comment]
Hello @nitsuj102284 

Composer is most likely working fine, it's probably a bit of confusion on your end and a bit of our fault by not having the documentation fully updated yet, as we have a work in progress overall refresh on the documentation.

Looking at the source code of the [Sources.php file](https://github.com/cartalyst/stripe/blob/2.0/src/Api/Sources.php), there's no `all()` method anymore.

Reason being, the [Stripe API documentation for Sources](https://stripe.com/docs/api#sources), doesn't have an all endpoint anymore either.
It used to be like that, and it probably still works, but if it's not documented it's preferable to not use it, and use what they recommend instead which is:

- `Stripe::cards()->all($customerId);` to retrieve cards of a customer
- `Stripe::bankAccounts()->all($customerId);` to retrieve bank accounts of a customer

Let me know if you have any further questions.

Cheers!

**Comment by nitsuj102284** [comment]
OK, so that helps that I don't have to update the files manually apart from Composer :). From their documentation, they still use 'sources' endpoint.

Using `Stripe::cards()->all()` and `Stripe::bankAccounts()->all()` shows both cards and bank accounts.

Api\BankAccounts.php
`public function all($customerId, array $parameters = [])
    {
        return $this->_get("customers/{$customerId}/sources", $parameters);
    }`

From the Stripe Documentation:
`curl "https://api.stripe.com/v1/customers/[customer_id]/sources?object=bank_account&limit=3"`

... it takes an 'object' parameter equal to "bank_account", so this
`Stripe::bankAccounts()->all($stripe_id, ['object' => 'bank_account'])`

gets just the bank accounts. Kind of wish that the Cartalyst API set the object in BankAccounts.php and Cards.php, just because it feels weird having to specify that we want bank account sources when calling `Stripe::bankAccounts()`.

**Comment by brunogaspar** [comment]
@nitsuj102284 Oh, that's probably my bad when i moved the methods around.

Want to send a pull request to fix that issue?

That would be super, since you're already digging into the code :)

If not i can look into it later today.

**Comment by nitsuj102284** [comment]
@brunogaspar, I'm kind of new to contributing and pull requests. So, for me this makes sense, and I'm sure that it would make sense to others too, but walk me thru this.

What if a developer is using this package already, and not passing an object. They know that they are getting bank accounts _and_ cards. So, updating the code would say that if 'object' is not set, set it to  "bank_account", but now, where they were expecting to receive both as before (because just a 'sources' class was not available to them), they only are receiving bank accounts.

How do you handle this potentially breaking change? I am curious of your thoughts.

Api\BankAccounts.php:
`
public function all($customerId, array $parameters = [])
    {
        $parameters['object'] = (isset($parameters['object']))
            ? $parameters['object']
            : 'bank_account';
        return $this->_get("customers/{$customerId}/sources", $parameters);
    }
`

Api\Cards.php:
`
public function all($customerId, array $parameters = [])
    {
        $parameters['object'] = (isset($parameters['object']))
            ? $parameters['object']
            : 'card';
        return $this->_get("customers/{$customerId}/sources", $parameters);
    }
`

**Comment by brunogaspar** [comment]
@nitsuj102284

> I'm kind of new to contributing and pull requests.

That's totally fine.

> So, for me this makes sense, and I'm sure that it would make sense to others too, but walk me thru this.

Yeap, as i stated on the previous reply, it's an issue/bug on the code.

> What if a developer is using this package already, and not passing an object.

If the developer is using these methods they are expecting those type of objects to be returned.
Example, for the `Stripe::cards()->all($customerId);` call it's only expected to return cards, and not cards and bank accounts which is what's happening currently, which is incorrect behaviour.

> How do you handle this potentially breaking change? I am curious of your thoughts.

I wouldn't call this a breaking change necessarily due to the fact that the methods are not doing what they should do in the first place. So this is more of a bugfix.

How i would do is, i would force the object to always be the required one at all times.

Even if you pass a different object type through the parameters, that would not be used.
That way it would enforce consistency on the response.

Code wise, i would just do

Api\Cards.php

```php
public function all($customerId, array $parameters = [])
{
    $parameters['object'] = 'card';

    return $this->_get("customers/{$customerId}/sources", $parameters);
}
```

Api\BankAccounts.php

```php
public function all($customerId, array $parameters = [])
{
    $parameters['object'] = 'bank_account';

    return $this->_get("customers/{$customerId}/sources", $parameters);
}
```

Do let me know your thoughts and if you prefer to do the pull request (it's not hard) or if i should go ahead and patch the code, will only be able to do that later tonight though :)

**Comment by nitsuj102284** [comment]
I started a pull request, but I don't think that I did it correctly. I cannot pull from latest (2.0).
