### ISSUE TITLE
How to update card no ?

### ISSUE THREAD

**Issue by kristoff2016** [cartalyst/stripe#103]
Hello,
thanks for your awesome library I do love it.
 I tried update card no 
```
$card = $stripe->cards()->update($user_sub->stripe_id, $user_sub->card_id, [ 
    'number'    => '4242424242424242',
    'exp_month' => 10,
    'cvc'       => 314,
    'exp_year'  => 2020,
] 
```
But I could not update it do you have any idea ?

**Comment by brunogaspar** [comment]
Hello @kristoff2016 

Stripe itself doesn't allow the card number to be updated.

You will need to delete and create a new card i believe.

You can see [here](https://stripe.com/docs/api#update_card) the parameters that Stripe officially allows to be passed when it comes to update cards.

Hope it helps.
