### ISSUE TITLE
Cannot Preview Prorate

### ISSUE THREAD

**Issue by nickashley** [cartalyst/stripe#107]
When giving the user the option to change/upgrade their subscription, Stripe allows you to set a prorate date, then preview what the immediate cost would be. With the Stripe SDK, this is done via the Subscription::upcoming method:  
https://stripe.com/docs/billing/subscriptions/prorations#previewing-proration

As far as I can tell, there is no way to do this currently with the Cartalyst package.

**Comment by nickashley** [comment]
I just noticed that this has been implemented in the master branch: 
https://github.com/cartalyst/stripe/commit/4fb9a703180f7bb83ecfcbba2bfc85dc15c0a9f5

So I guess I just need to wait until the next version is released - any idea when that would be?

Thanks!

**Comment by brunogaspar** [comment]
Will be available on the next release, 2.1.5.
