### ISSUE TITLE
Products and plans for newest API version (2018-09-06)

### ISSUE THREAD

**Issue by davidosuna1987** [cartalyst/stripe#108]
Hello!

I'm trying to use your awesome package with my new project, but I need to use subscriptions to plans, and in newest API version (2018-09-06) to create plans, you must to link plan with a product (one product can have several plans)...this functionality is not included into cartalyst plans function.

You think that you implement this functionality?

Very thank you!!

**Comment by TechTailor** [comment]
Would appreciate the addition as well.

**Comment by brunogaspar** [comment]
Hello

This was already possible for quite some time.

While the products API is used for goods and services, the endpoint is the same.

Do let me know if there's any issue.

Thanks!
