### ISSUE TITLE
How to add bank account to user which created with stripe ?

### ISSUE THREAD

**Issue by kristoff2016** [cartalyst/stripe#110]
Hello, 
First, I would like to thank you for great plugin. 
Currently, I tried to implement the featured that allowing user update their account profile and add the bank account into their as well. 

I could not found any example. Please help me how I implement this featured I can implement the update the credit card but really don't know how to allow user add their bank account to stripe via your plugin.

Thank you so much.

**Comment by mprythero** [comment]
Interested in this as well, at the moment, it appears that you are only allowed to create a one-time use token for a bank account, but cannot directly associate it with a Stripe customer like you can with a card. Did you find a way to work with this since you were the one who closed it?
