### ISSUE TITLE
SCA (Strong Customer Authentication)

### ISSUE THREAD

**Issue by jamesliscombe** [cartalyst/stripe#117]
New EEA (European Economic Area) regulation will require all electronic payments to be SCA compliant from September 2019.

Are there plans to have Cartalyst implementing the Stripe changes which are planned for early 2019?

Currently this framework can't create payment intents.

Regards,

**Comment by jamesliscombe** [comment]
That’s great. I want to stick with Cartalyst, I’ll keep checking the documentation throughout this year. 
Thanks

**Comment by GrahamCampbell** [comment]
Any news on this? ;)

**Comment by ConnorVG** [comment]
Any news yet?
