### ISSUE TITLE
Using idempotency_key

### ISSUE THREAD

**Issue by blorange2** [cartalyst/stripe#118]
When using your package to create a charge I had an issue where a user could click the submit button multiple times and submit multiple charges. 

I read in the official Stripe documentation that you can set a idempotency_key on the Charge object to avoid such situations.

So, I tried the following:

    $charge = $stripe->charges()->create([
        'amount' => $amount,
        'currency' => $currency,
        'card' => $token,
        'description' => $description,
        'statement_descriptor' => 'Newable Ventures',
        'receipt_email' => $user->email
      ], [
            "idempotency_key" => $user->id
      ]);

I also see that the package uses a Stripe config file at `vendor\cartalyst\stripe\src\Config.php`

This file contains the following:

    /**
     * {@inheritdoc}
     */
    public function setIdempotencyKey($idempotencyKey)
    {
        $this->idempotencyKey = $idempotencyKey;

        return $this;
    }

So, you can set it, however when I send the request I do not see the additional key anywhere.

**Comment by brunogaspar** [comment]
@blorange2 I'm assuming that the example you gave was a copy paste from the official Stripe documentation. The majority of the examples from there doesn't entirely work on this library, as the underlying code is totally different :)

See if the following works as expected:

```php
$charge = $stripe->idempotent($user->id)->charges()->create([
    'amount' => $amount,
    'currency' => $currency,
    'card' => $token,
    'description' => $description,
    'statement_descriptor' => 'Newable Ventures',
    'receipt_email' => $user->email
]);
```

> Notice i'm calling `->idempotent()`method before `->charge()->create([..])`

**Comment by blorange2** [comment]
Without sounding dense, or rude, is this documented anywhere?

I'll give your solution and try and get back to you.

**Comment by brunogaspar** [comment]
It's not documented, but you're free to submit a pull request updating the documentation if you feel like it.

**Comment by blorange2** [comment]
That solution worked as expected, I could see the key in my Stripe dashboard.

Thanks again.

I've never updated documentation but I will read into it and make this addition.

**Comment by brunogaspar** [comment]
Glad it worked and no worries about the documentation, i'm sure i'll get it updated soon :)
