### ISSUE TITLE
One subscription with multiple plans

### ISSUE THREAD

**Issue by jurtjee1997** [cartalyst/stripe#120]
I'm looking for the documentation for implement multiple plans inside a subscription. I saw this issue but I did not get any wiser [(81)](https://github.com/cartalyst/stripe/issues/81). 

I tried with this but that did not work:
```
$subscription = $stripe->subscriptions()->create('customer_d', [
    ['plan' => 'plan_id', 'quantity' => 2],
    ['plan' => 'plan_id', 'quantity' => 1]
]);
```
Error:
`"message": "Received unknown parameters: 0, 1"`

can someone help me?

**Comment by jurtjee1997** [comment]
Thank you, but how can i update it with:
```
$subscription = $stripe->subscriptions()->update('customer_d', 'subscription_id' [
    'items' => [
        ['plan' => 'plan_id', 'quantity' => 3],
        ['plan' => 'plan_id', 'quantity' => 1]
    ],
]);
```

Error:
`"Cannot add multiple subscription items with the same plan:"`

**Comment by brunogaspar** [comment]
As far as i'm aware, you can't attach the same plan multiple times to a single subscription. For that you would need to create 2 subscriptions and apply that plan.

That's how Stripe works and there's nothing we can really do i don't think. If you try with their dashboard, i believe you'll get similar results.

Hope it helps.

**Comment by jurtjee1997** [comment]
you can change the quantity but how??

**Comment by brunogaspar** [comment]
You'll need to pass the Subscription Item ID.

The Subscription Item ID starts with `si_` and is returned when you create a subscription inside the `items` array, you just need to check the data that Stripe returns after you create a Subscription.

To update a Subscription Item you have 2 ways of doing it, i think.

This way, while it's longer, it allows you to update multiple items in one go:

```php
$subscription = $stripe->subscriptions()->update('cus_EN6H74Usa87pFT', 'sub_EN6HOANAifYe3v' [
    'items' => [
        ['id' => 'si_EN6H3xImJT5sU3', 'quantity' => 2],
    ],
]);
```

Or this way, more compact, but, you're only allowed to update one item at a time:

```php
$subscription = $stripe->subscriptionItems()->update('si_EN6H3xImJT5sU3', [
    'quantity' => 2,
]);
```

You can also use the Subscription Items to attach new item(s) to a Subscription or to even remove item(s) if you need to as well.

Hope it helps.

**Comment by jurtjee1997** [comment]
When i downgrade a subscription item, wil it be charge this month? and how can i delete a subscriptionItems? quantity 0?

**Comment by brunogaspar** [comment]
> When i downgrade a subscription item, wil it be charge this month?

You'll need to pass the `prorate` flag to indicate Stripe that you want it to be prorated i suppose?

Here's documentation about [Prorations](https://stripe.com/docs/billing/subscriptions/prorations).

> How can i delete a `subscriptionItems`? quantity 0?

You can delete a Subscription Item by calling `$stripe->subscriptionItems()->delete('si_EN6H3xImJT5sU3');

> Can you link the docs for `subscriptionItems()`?

It's not documented at the moment i'm afraid.

Hope it helps 🍻
