### ISSUE TITLE
Odd Idempotency Key Model

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#123]
I thought the point of an idempotency key is something that is unique per operation. Thus, why would someone want to set it when creating a client? Surely this should be something set every time we want to "do something", not when we want to create, say, a cards client instance?

**Comment by brunogaspar** [comment]
It's really up to you to decide if your requests are idempotent or not, not me or the library.

Therefore, you can enable on a per request basis or globally on your project and have a way to have the key unique per the request you're doing.

Having it on the Client level was the cleanest and easiest way to achieve, if you have other way to simplify it, you are more than welcome to submit a pull request.

**Comment by GrahamCampbell** [comment]
But then I have to create a new client over and over?

**Comment by GrahamCampbell** [comment]
> Therefore, you can enable on a per request basis or globally on your project and have a way to have the key unique per the request you're doing.

But that's not how the code works. One must set a distinct idempotency key for each distinct operation. The code here only allows a single key to be set.

**Comment by brunogaspar** [comment]
Then propose a better way i guess?

**Comment by brunogaspar** [comment]
Just an idea, that seems doable to implement, and can/should be backwards compatible (without the need to move or remove the current `Stripe::idempotent` behaviour).

```php
Stripe::charges()->idempotent('charge123456789')->create([...]);
```

Basically, there will be a `idempotent(:key)` method on the API class, then when the header is set, it can keep backward compatibility.

I haven't tested this, but seems doable and fixes the issue i assume?

Will assert tomorrow and push the changes as well.

**Comment by GrahamCampbell** [comment]
Yes, I was just thinking about this this morning on the train. That was the identical solution I was going to propose. :)

**Comment by brunogaspar** [comment]
Cool, please check https://github.com/cartalyst/stripe/pull/124 whenever you have time.

Only added one test though, but should show it works, hopefully.

**Comment by GrahamCampbell** [comment]
I've left some feedback .:)
