### ISSUE TITLE
Received unknown parameter: requested_capabilities

### ISSUE THREAD

**Issue by dominik-wbz** [cartalyst/stripe#126]
Trying to create an account for Stripe Connect with Stripe-provided example:

```
\Stripe\Account::create([
  "type" => "custom",
  "country" => "US",
  "email" => "bob@example.com",
  "requested_capabilities" => ["card_payments"]
]);
```

This produces an error of: Received unknown parameter: requested_capabilities

When I remove 'requested_capabilities' the account is created but requested_capabilities is required for sending payments.

Also other parameters like business_type which is also required for my use cannot be used.

Can you help me? Thanks

**Comment by brunogaspar** [comment]
Hello @dominik-wbz 

From the code example above, it seems you're using the official [Stripe library](https://github.com/stripe/stripe-php) and not this one.

But either way, the issue you're having seems to related to the Stripe version.

Either the library is send an old Stripe Version or your API Version is old and the version required is at least `2019-02-19`.

For setting the Stripe Version on the library itself, you'll need to check their documentation.

For updating the API Version, you can update [through the Stripe Dashboard](https://dashboard.stripe.com/developers).

Hope it helps :)
