### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by lukadriel7** [cartalyst/stripe#127]
Hello, I have been planning to use stripe cartalyst for my platform because it seems simpler than the regular stripe API and has a Laravel integration. I was waiting for the implementation of payment intents before moving forward, which was implemented in 2.2 it seems. Unfortunately I didn't find any documentation about the new features. Is there any plans to update the documentations or any place I can learn more about it ?
Thanks again for the great package

**Comment by brunogaspar** [comment]
Hello @lukadriel7 

Yes, you're totally right, i've been slacking a bit on documentation.

But for now, i believe you can get along on how to use Payment Intents from the tests [here](https://github.com/cartalyst/stripe/blob/2.2/tests/Api/PaymentIntentsTest.php) which i think is straightforward, but of course, do let me know if you find issues or have questions :)
