### ISSUE TITLE
subscriptions create with the "default_tax_rates" array gives a invalid_request_error /  parameter_unknown

### ISSUE THREAD

**Issue by ibrainventures** [cartalyst/stripe#131]
If i try with the cartalyst routine :

```
        $subscription = Stripe::subscriptions()->create('cus_FL5Y********ZCO', [
                    'plan' => 'a-existing-plan-name',
                    'default_tax_rates' => ["txr_1EqLfuLaI0owzRPtbAyn8ogk"],              
        ]);
```

the stripe api gives me : "invalid_request_error"  or  array_error or parameter_unknown

with the origin stripe-php following is working:

```
        $subscription =  Subscription::create([
              "customer" => "cus_FL5Y*******ZCO",
              "default_tax_rates" => ['txr_1EqLfuLaI0owzRPtbAyn8ogk'],
              "items" => [
                [
                  "plan" => "a-existing-plan-name",
                ],
              ]
            ]);
```
this creates a api post with:

```
{
  "customer": "cus_FL5Y********ZCO",
  "default_tax_rates": {
    "0": "txr_1EqLfuLaI0owzRPtbAyn8ogk"
  },
  "items": {
    "0": {
      "plan": "a-existing-plan-name"
    }
  }
}
```

https://stripe.com/docs/api/subscriptions/create#create_subscription-default_tax_rates

any idea how i can solve this issue ?

**Comment by brunogaspar** [comment]
You'll need to pass the same payload where the plan is inside an items array.

**Comment by ibrainventures** [comment]
Hi, 

did you mean so : ? .. This is also not working ...  

Can you give me please a hint ...      

   $subscription = Stripe::subscriptions()->create('cus_FL5YO******3ZCO', [
                "items" => [
                    [
                        "plan" => "plan",
                        "default_tax_rates" => ['txr_1EqLf*****Ayn8ogk'],   
                    ],
                ]
        
        ]);

**Comment by ibrainventures** [comment]
default_tax_rates is something other than tax_percent ... tax_percent is working .. but default_tax_rates is not ..

**Comment by brunogaspar** [comment]
Something like this:

```php
$subscription = Stripe::subscriptions()->create('cus_FL5YO******3ZCO', [
    "default_tax_rates" => ['txr_1EqLf*****Ayn8ogk'],   
    "items" => [
        [
            "plan" => "your-plan-id-here",
        ],
    ]
]);
```

It should work as expected that way

**Comment by ibrainventures** [comment]
nope .. same error .. as i got the last 6 hours  .. 

 Cartalyst \ Stripe \ Exception \ MissingParameterException (400)
Received unknown parameter: default_tax_rates

on the dashboard:
{
  "default_tax_rates": [
    "txr_1EqLfuLaI0******tbAyn8ogk"
  ],
  "items": [
    {
      "plan": "plan-name"
    }
  ]
}

... 

2 possibilities:

1) the stripe api has a bug with this post-type (the customer id inside the uri instead of post param)

POST /v1/customers/cus_FL5Y*********/subscriptions

or

2) 

this default_tax_rate must have this "0" before .. ???

:::
Methode POST
URL /v1/subscriptions
Status 200
Stripe/v1 PhpBindings/6.39.0

----> this POST-type of the origin Stripe Php is working ..:


```
> 
> {
>   "customer": "cus_FL5YOv****y3ZCO",
>   "default_tax_rates": {
>     "0": "txr_1EqLfuLaI0ow****bAyn8ogk"
>   },
>   "items": {
>     "0": {
>       "plan": "plan"
>     }
>   }
> }
```

**Comment by brunogaspar** [comment]
> this default_tax_rate must have this "0" before .. ???

The indexes are not needed to be passed.

Unfortunately, i'm not able to reproduce the problem on my end with the code above.

I can send the request as expected (of course it errors out since i don't have  that tax rate and it would fail for the plan as well)

![Screen Shot on 2019-06-29 at 00:48:00](https://user-images.githubusercontent.com/2285372/60376541-982c4f00-9a07-11e9-818d-d35927b32fa9.png)

**Comment by ibrainventures** [comment]
Hi Bruno,

testing with those params / no existing tax-rate id .. is giving me the same error response like your test .. 

But .. with existing plan und tax-rate it is not working .. definitily .. 

So .. please . if you have the little-time ..  you can easily create a  tax-rate in the dashboard
and may you have a exisitng plan inside your test-data-area

https://dashboard.stripe.com/test/tax-rates

You would help me a lot .. and i am double sure .. that there is a bug / incompatibility with your extension ...

I am working with your extenstion now since 6 month and it would be a hard pain to go back to the origin stripe-extension ..

Please .. if it is working out-of-the box .. and i am wrong .. i would donate a amount to a non profit organisation ..

**Comment by brunogaspar** [comment]
Alright, i see what's wrong and also seems a breaking change from Stripe as after running the test suite of this package, it's now breaking a lot.

Basically they don't allow the old endpoints like is `customers/{$customerId}/subscriptions"` to be used when you pass for example very new stuff like this `default_tax_rates`.

Will try to do a release with this fixed later today if i don't notice the tests breaking a lot.

**Comment by ibrainventures** [comment]
.. i am happy, that this issue is also happening on your side .. ;-)

Stripe is  working hard on doing their best to not loosing all re-billings after 14th September 2019,
because of the SCA / PSD2 rules ..

https://stripe.com/docs/strong-customer-authentication/connect-platforms#saving

If i read it right, all European Customers / Subscriptions can / are affected ...

There is also a info:

> . **An API to perform a**uthentication when saving a payment method **will be available by July 1, 2019. Y**ou should update your integration today and make incremental changes after July 1st to reduce the rate at which customers need to authenticate their payment method.
.
May you can re-open the issue , maybe there are other people who sitting out and have issues ?

**Comment by brunogaspar** [comment]
Pushed a fix, hopefully it works as expected for you now.

Do a `composer update` and give it a try please.

**Comment by ibrainventures** [comment]
wohoooa ! .. composer updated .. and tested with those styles:

```
        $subscription = Stripe::subscriptions()->create('cus_FL5YOttttt3ZCO', [
            "default_tax_rates" => ['txr_1EqLfttttttAyn8ogk'],   
            "plan" => "a-plan",
            "cancel_at_period_end" => true, 
        ]);
```

and:
```
$subscription = Stripe::subscriptions()->create('cus_FL5YOttttt3ZCO', [
    "default_tax_rates" => ['txr_1EqLfttttttAyn8ogk'],   
    "items" => [
        [
            "plan" => "a-plan",
        ],
    ]
]);        
```
--> works without any problems, and the tax-rates are included!

also testet some paymentIntent create and confirms .. all works fine .. 
Inside the logs i saw, that the uri now without `$customer ` sent  ...

PERFECT .. what a great weekend ..

I wish you all the best and 👍 👍 👍
