### ISSUE TITLE
New Stripe API Setupintents ... 

### ISSUE THREAD

**Issue by ibrainventures** [cartalyst/stripe#135]
Hi Bruno,

the stripe-think-tank has work done ::

**Setupintents** 
https://stripe.com/docs/api/setup_intents

there we can go for handling also the SCA for Subscription ..

Any timeplan for wrapping this interface ?

**Comment by brunogaspar** [comment]
I'll get to it today.

**Comment by GrahamCampbell** [comment]
:rocket:
