### ISSUE TITLE
I can't fix this error

### ISSUE THREAD

**Issue by MichleLI** [cartalyst/stripe#137]
I am going to create subscription using cartalyst.
please help me!
$subscription = $stripe->subscriptions()->create('cus_FPXFPVGROcb70E', [
      'plan' => 'monthly_1',
 ]);
![image](https://user-images.githubusercontent.com/45660446/60993821-cb64cb80-a381-11e9-81cf-666cde7d82db.png)

**Comment by brunogaspar** [comment]
Hello @MichleLI 

Our documentation is a tad outdated, we're working on updating it.

In the mean time, you'll need to pass an items array where it would contain another array for each plan you want your subscription to have and other relevant information like quantity etc...

Something like this:

```php
$subscription = $stripe->subscriptions()->create('cus_FPXFPVGROcb70E', [
    'items' => [
        [
            'plan' => 'monthly_1',
        ],
    ],
]);
```

Let me know if that helps.

**Comment by MichleLI** [comment]
![image](https://user-images.githubusercontent.com/45660446/60998938-8c884300-a38c-11e9-9a11-e23f99ce8de9.png)
changed error status!

**Comment by GrahamCampbell** [comment]
For me, I don't pass items, and it works.

```
$subscriptions->create('CUST_ID', ['plan' => 'PLAN_ID']);
```

**Comment by GrahamCampbell** [comment]
Is your plan ID correct. That is probably why Stripe is complaining. Make sure you add it in both live and test mode, that is, if you only created the plan in live mode. Plans and products are distinct between live and testing.

**Comment by MichleLI** [comment]
![image](https://user-images.githubusercontent.com/45660446/60999296-61522380-a38d-11e9-9889-f29ae6867e27.png)

**Comment by MichleLI** [comment]
I hope you to help me
please help me!

**Comment by GrahamCampbell** [comment]
I don't see why this wouldn't work. Are you using the test mode secret key?

**Comment by MichleLI** [comment]
yes, I am using test secret key.

**Comment by GrahamCampbell** [comment]
What did you set as the API version?

**Comment by MichleLI** [comment]
2.2.8(cartalyst 10)

**Comment by GrahamCampbell** [comment]
The API version will look like a date. For example, `2019-05-16` is the latest.

**Comment by GrahamCampbell** [comment]
This library is hard coded to use `2017-06-05` if no version is supplied. Maybe try with `2019-05-16`?

**Comment by brunogaspar** [comment]
Does that customer you're passing exist?

Go into the Logs page https://dashboard.stripe.com/test/logs and click on one that gave a 400 so you can see what Stripe is complaining.

Also as @GrahamCampbell suggested, use the newer version too.

**Comment by MichleLI** [comment]
can you help me via anydesk. so sorry!
850 612 738

**Comment by MichleLI** [comment]
![image](https://user-images.githubusercontent.com/45660446/61000049-2cdf6700-a38f-11e9-8591-c8f6037fa766.png)

**Comment by brunogaspar** [comment]
According to your last image, the customer does not have any card attached.

You'll need to first associate a card to the customer then you can create the subscription.

**Comment by GrahamCampbell** [comment]
Stripe Elements is a simple way to setup this.

**Comment by GrahamCampbell** [comment]
https://stripe.com/docs/stripe-js/elements/quickstart

**Comment by MichleLI** [comment]
we have to use this script?
<script src="https://js.stripe.com/v3/"></script>

**Comment by GrahamCampbell** [comment]
Among other things. Have a full read of their docs so you get a feel for the terminology and what's going on. Be prepared to spend a couple of hours setting up Elements.

**Comment by MichleLI** [comment]
Thanks GrahamCampbell and brunogaspar!

**Comment by brunogaspar** [comment]
You're welcome.

Let us know if you have other questions or issues.

Regards!
