### ISSUE TITLE
Payment intents impossible to use

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [cartalyst/stripe#142]
i'm using payments intent and i'm trying to use it without the documentation, taking in account that there is no documentation on this... but, how can i understand for example what you mean about PaymentIntent o Webhook ''$parametes'' if there is no ''$parameters'' array example on the comments below? can you please put a comment with the options available and what that means? or giving a possibile release date for the proper documentation?

**Comment by brunogaspar** [comment]
It's as simple as:

```php
$paymentIntent = Stripe::paymentIntents()->create([
    'amount' => 3000,
    'currency' => 'USD',
]);

echo $paymentIntent['client_secret'];
```

Same goes for Setup Intents, which you don't need to pass anything if you don't want to:

```php
$setupIntent = Stripe::setupIntents()->create();

echo $setupIntent['client_secret'];
```

For now, you can refer to the tests as they give you good examples:
- https://github.com/cartalyst/stripe/blob/2.2/tests/Api/PaymentIntentsTest.php
- https://github.com/cartalyst/stripe/blob/2.2/tests/Api/SetupIntentsTest.php

Also it's recommended to read the Official Stripe API documentation to understand the parameters you can send on each:
- https://stripe.com/docs/api/payment_intents/create
- https://stripe.com/docs/api/setup_intents/create

Hope it helps.

**Comment by AlbertoSinigaglia** [comment]
yes but how i can manage WebHook? on the tests i can see how to manage a WebHook, but there is no ''handler'' for it... i mean, as Stripe documentation says, they will send a request to a given route with the information about a PaymentIntent that has changed his status... how can i handle it? i'm referring to [this page](https://stripe.com/docs/payments/payment-intents/verifying-status#webhooks)

**Comment by brunogaspar** [comment]
Ah well, this package is not meant to handle Webhooks (receive the requests), it is just an API client for the Stripe API.

But to shed some light on what you need to do, you need create a dedicated route (i assume you're on Laravel) that receives a `POST` request from Stripe, there you can perform the necessary actions based on what Stripe sends through the Webhook.
