### ISSUE TITLE
Corresponding method

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [cartalyst/stripe#143]
can't find the corresponding [method referred on this page](https://stripe.com/docs/payments/payment-intents/verifying-status#webhooks) as `\Stripe\Webhook::constructEvent` 
i've checked on stripe/src/Api/Events and on stripe/src/Api/WebhookEndpoints but ive found nothing about it, also i can't find any test about it

**Comment by brunogaspar** [comment]
Sorry, but this package only supports the API endpoints that are on the [Stripe API Spec](https://stripe.com/docs/api).

This unfortunately is not on their API Spec, therefore it's something we can't support and you'll need to build it in your application.

However, there's already a few Laravel packages that solves this problem for you, just search for Laravel Stripe Webhook on Google or GitHub and i'm sure you'll find it.

Thanks!
