### ISSUE TITLE
Creating a source for an existing customer

### ISSUE THREAD

**Issue by xitude** [cartalyst/stripe#144]
Following stripes doc's [here](https://stripe.com/docs/sources/customers#attaching-a-source-to-an-existing-customer-object).

I should be able to create a new source for an existing customer, could you direct me to the correct place in the documentation to create this via cartalyst?

Thanks

**Comment by brunogaspar** [comment]
Hey @xitude 

I need to add docs for Sources, thought i had them..

But for now creating a Source can be done by doing something like the following:

```php
$source = Stripe::sources()->create([
    'type' => 'ach_credit_transfer',
    'currency' => 'usd',
    'owner' => [
        'email' => 'john@doe.com',
    ],
]);
```

The parameters of the array you can find [here](https://stripe.com/docs/api/sources/create).

Similar API for update and deletion, but you pass the Source ID as the first argument of each method.

Will keep the issue open so i don't forget about pushing docs for this.

Do let met know if you have issues or other questions.

**Comment by xitude** [comment]
Thanks, Im integrating SEPA at the moment so it would be good to add that to documentation.
