### ISSUE TITLE
WebHook validation

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [cartalyst/stripe#145]
in Stripe API docs, inside webhook validation, there is 
```php
$event = \Stripe\Event::constructFrom(
        json_decode($payload, true)
);
```
in this library exists the ''Stripe\Event'' element?

**Comment by brunogaspar** [comment]
Hi @AlbertoSinigaglia 

hmm not sure what that `constructFrom` method does, but i guess we don't have that behavior.

But if it's to validate a webhook, we don't provide any webhook validation on this library, as that's a bit out of the scope of this library i'm afraid.

But you can fetch events with our library https://cartalyst.com/manual/stripe/2.0#events just does not have webhook validation if t hat's what you're after.

Hope it helps.
