### ISSUE TITLE
How to create customer with token

### ISSUE THREAD

**Issue by BaiMaoLi** [cartalyst/stripe#154]
I need to create customer with token.
But it is giving error "token not supported"
Please help me.
Thanks. best cheers

**Comment by brunogaspar** [comment]
Not sure what you by creating customer with token.

Please elaborate and paste some code so i can try to understand what you're trying to achieve.

**Comment by martinjankov** [comment]
@BaiMaoLi It would've been nice to write if you solved it and how before closing the issue
