### ISSUE TITLE
 Call to undefined method Cartalyst\Stripe\Stripe::recipients()

### ISSUE THREAD

**Issue by raoikram** [cartalyst/stripe#155]
### Your Environment

- OS and Version: 64 Bir Windows 10
- PHP Version: 7.2.19
- Stripe Laravel Version: 11.0.*

### Expected behaviour

*Please describe what you are expecting to see happening.*
i was trying to create recipients but i sae this error on api call.

### Actual behaviour
  $recipient = $stripe->recipients()->create([
            'name' => 'John Doe',
            'type' => 'individual',
        ]);
        dd($recipient);
It saying :

Cartalyst\Stripe\Exception\MissingParameterException: Recipients have been deprecated and are no longer available. They have been replaced by Custom accounts (see https://stripe.com/docs/connect/recipient-account-migrations), which you should use if you're creating a new platform. Please reach out at https://support.stripe.com/contact if you have any questions. in file C:\laragon\www\rtn2-backend\vendor\cartalyst\stripe\src\Exception\Handler.php on line 125

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*
1. install your package from **https://cartalyst.com/manual/stripe/2.0#laravel**
2. then in  controller i created  function
use Cartalyst\Stripe\Stripe;

    public function StripeRecipients(Request $request)
    {
      $recipient = $stripe->recipients()->create([
            'name' => 'John Doe',
            'type' => 'individual',
        ]);
        dd($recipient);
    }
3. call the api.

**Comment by raoikram** [comment]
@brunogaspar I need a little help if you dont mind i was trying to create customer account 
I created Customer Through this
  $customer = $stripe->customers()->create([
            'email' => $request['customer_email'],
        ]);

it works after that  i need to send payment on this account so i need to create account 
$account = $stripe->account()->create([
                'type' => 'custom',
                'country' => 'GB',
                'email' => 'bob@example.com',
                'requested_capabilities' => [
                    'transfers',
                ],
            ]);
but when i try to create account it gives me error

Cartalyst\Stripe\Exception\MissingParameterException: Your platform needs approval before giving accounts the platform_payments capability. in file C:\laragon\www\rtn2-backend\vendor\cartalyst\stripe\src\Exception\Handler.php on line 125

Can You help me i study capability on stripe but i dont know whats the issue is

**Comment by brunogaspar** [comment]
@raoikram I believe you need to verify your Stripe account in order for your connected accounts to use such capabilities, but, i can be totally wrong hehe

Relevant documentation:
- https://stripe.com/docs/connect/required-verification-information
- https://stripe.com/docs/connect/managing-capabilities

**Comment by raoikram** [comment]
the account is verified and

studying this already https://stripe.com/docs/connect/managing-capabilities

**Comment by brunogaspar** [comment]
Then i would reach out to Stripe support, they will be able to support on that problem way better than me :)

**Comment by raoikram** [comment]
ok thanks i will reach them out :p

**Comment by brunogaspar** [comment]
Awesome. But do let me know if you still get stuck after their reply, so i can further investigate it if needed.

**Comment by raoikram** [comment]
Yes I asked them their agent said our technical team will email You after investigating the issue you explained to me
