### ISSUE TITLE
How to create payment method with card id?

### ISSUE THREAD

**Issue by BaiMaoLi** [cartalyst/stripe#156]
I need to create payment method from existing card id.
But I could not handle by your documentation.
If there is any way, please let me know.
Thanks

**Comment by brunogaspar** [comment]
Hey

So, you have a Card object on Stripe and you want to convert it to a Payment Method?

**Comment by BaiMaoLi** [comment]
Hello.
Sorry, it was my false,
When I have cards, i only have to do default_source when creating subscription.
No need to create payment method by card id.

**Comment by BaiMaoLi** [comment]
So, it is solved, and I am closing.
Thanks for your support.
