### ISSUE TITLE
paymentIntentSetup - Unknown parameter

### ISSUE THREAD

**Issue by aalicki** [cartalyst/stripe#159]
After reviewing the docs, test case, and examples, it seems that the parameter "confirm" (which is expected to be true or false), is not accepted as a parameter when running `$stripe->paymentMethods()->create`

For example:
```

\Cartalyst\Stripe\Laravel\Facades\Stripe::paymentMethods()->create([
            'type'      => 'card',
            'confirm'   => true, //Problem parameter
            'card' => [
                'number'    => $request->get('inputCCNum'),
                'exp_month' => $request->get('exp_month'),
                'exp_year'  => $request->get('exp_year'),
                'cvc'       => $request->get('cvc')
            ],
        ]);
```

The error received when attempting to run the code with the confirm param is "Received unknown parameter: confirm "

Edit: Unless this is the wrong documentation, the params and calls are improperly documented it appears - https://cartalyst.com/manual/stripe/2.0#setup-intents

**Comment by GrahamCampbell** [comment]
>                 'number'    => $request->get('inputCCNum'),

Is that the raw credit card number? Absolutely **do not do this** unless you have some very special reason you need this and want to go through the regularity steps to be permitted to handle raw credit card data within your backend.

The expected way to use this API is to have Stripe JS generate a special token, and have that sent to your backend server. Stripe provide JS implementations that make things easy for you so much so they can pre-fill a PCI compliance form for you. https://stripe.com/gb/guides/pci-compliance

**Comment by brunogaspar** [comment]
@aalicki You're linking to the Setup Intents docs, but you're using the Payment Methods API on your example code.

The documentation you want is https://cartalyst.com/manual/stripe/2.0#create-a-payment-method but it can happen to be outdated, if it's you can check https://stripe.com/docs/api/payment_methods/create which is the source of truth of the "parameters" you can pass.

Hope it helps.

**Comment by aalicki** [comment]
@GrahamCampbell - I was basing the initial working example off of the Stripe docs (and this library's docs) strictly. I've since moved over to tokenized card data and realized this library wasn't a good fit for the platform's needs. The idea was to never expose the CC data to any aspect of the backend, ended up using the Stripe library directly and Elements.

**Comment by brunogaspar** [comment]
>  I've since moved over to tokenized card data and realized this library wasn't a good fit for the platform's needs. The idea was to never expose the CC data to any aspect of the backend, ended up using the Stripe library directly and Elements.

Care to elaborate what was bad or wrong on this library so it can be improved?

**Comment by aalicki** [comment]
Sure!

For example, https://cartalyst.com/manual/stripe/2.0#setup-intents - it gives some overview on the SetupIntent, but then uses a "paymentMethod" end point, which is incorrect. It should be using "setupIntents" if I recall correctly.

The example code in this particular section also demos using the customer's explicit card information, a PCI violation I believe. I was using this for developing a Crowdfunding platform. 

The stuff regarding updating / creating a customer were fine, as were the charging of a payment.

**Comment by brunogaspar** [comment]
> For example, https://cartalyst.com/manual/stripe/2.0#setup-intents - it gives some overview on the SetupIntent, but then uses a "paymentMethod" end point, which is incorrect. It should be using "setupIntents" if I recall correctly.

That example is indeed incorrect, you could've submitted a pull request to fix it, it's open source after all :)

> The example code in this particular section also demos using the customer's explicit card information, a PCI violation I believe. I was using this for developing a Crowdfunding platform.

Yes, i totally get your point, probably it could have both examples, one for card details and another for the Stripe.js

It's only a PCI violation if you're not compliant with it, it's not forbidden or even prohibited to do it like that, it's a matter of understanding how payments online work in general, but either way, Stripe also demos it [like that](https://stripe.com/docs/api/payment_methods/create?lang=php) just for your information.

This documentation is just a very very very small mirror of what Stripe API documentation has to offer, which is quite difficult to always keep up to date and synced, since they are changing stuff all the time (thankfully) :)

But it's all good, thank you for the feedback, i really appreciate honest feedback!

**Comment by aalicki** [comment]
My apologies! I'm sorry if I came off rude or entitled!

I may try to circle back around and submit a PR regarding this and contribute back. I do think the library has a lot of the cases and needs covered for Stripe and it's very promising.

**Comment by brunogaspar** [comment]
> My apologies! I'm sorry if I came off rude or entitled!

Not at all, it's all good ;)
