### ISSUE TITLE
Recipients have been deprecated and are no longer available

### ISSUE THREAD

**Issue by ayman-elmalah** [cartalyst/stripe#160]
### Laravel valet

- OS and Version: macos
- PHP Version: 6.x
- Stripe Laravel Version: 2

I need to transfer money from my account to different bank accounts
so i need to add Recipient and transfer to them
so i use this method from docs
$recipient = $stripe->recipients()->create([
    'name' => 'John Doe',
    'type' => 'individual',
]);

### Expected behaviour

* may be any success message

### Actual behaviour

* Recipients have been deprecated and are no longer available. They have been replaced by Custom accounts (see https://stripe.com/docs/connect/recipient-account-migrations), which you should use if you're creating a new platform. Please reach out at https://support.stripe.com/contact if you have any questions.

**Comment by brunogaspar** [comment]
As recommended by Stripe and also as @GrahamCampbell correctly pointed out, you should use a different API, in this case is the Accounts API.

Renaming or even modifying the Recipients API on this library, albeit being deprecated is a breaking change as it still works on old Stripe API Versions.

Hope you understand.

Regards.
