### ISSUE TITLE
Passing amount to payment intents as "cents" getting multiplied by 100

### ISSUE THREAD

**Issue by reganjohnson** [cartalyst/stripe#165]
When creating a payment intent, the `amount` is inconsistent with expected and documented behaviour.

My request:
```
$paymentIntent = Stripe::paymentIntents()->create([
    'amount' => 7932,
    'currency' => 'usd',
    'customer' => 'cus_GvxABCD9cQRmCz',
    'payment_method' => 'pm_1GO5IEI0F6xy76h25VfkduyV',
    'off_session' => true,
    'confirm' => true,
]);
```
Is processed and sent to Stripe as the following parameters:
```
amount=793200&currency=usd&customer=cus_GvxABCD9cQRmCz&payment_method=pm_1GO5IEI0F6xy76h25VfkduyV&off_session=true&confirm=true
```

Going off documentation for payment intents create
https://cartalyst.com/manual/stripe/2.0#payment-intents

Key | Required | Type | Default | Description
-- | -- | -- | -- | --
amount | required | boolean | required | A positive integer representing how much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge ¥100, a zero-decimal currency).

A few things are wrong in the docs - firstly, this is not a boolean. Second, it is saying to pass in the smallest currency unit, however, when inspecting the code, it shows this is only true for a certain number of currencies as defined in `\Cartalyst\Stripe\Utility::prepareParameters` which all `_post` requests are filtered through.

`\Cartalyst\Stripe\Utility::needsAmountConversion` is returning `true` unless there is no currency or is one of the defined currencies.

This is contradicts the documentation, and also contradicts how Stripe recommends storing money and how you would use the native Stripe API (always dealing with cents).

**Comment by brunogaspar** [comment]
Hi

> A few things are wrong in the docs - firstly, this is not a boolean.
> This is contradicts the documentation

You're more than welcome to submit a pull request to address that, it's open source :)

> Second, it is saying to pass in the smallest currency unit,

That's true and should say that or in "dollars", though we have a "function" that tries to figure out the value you're passing is in cents or not and converts it to cents if it needs it.
In your case it seems it's not detecting it properly, so you have 2 options:
- Pass in "dollars"
- Pass in cents but disable the currency converter by doing `Stripe::disableAmountConverter()` anywhere on your code, as long as it's before performing any request.

Hope it helps!

Regards

**Comment by reganjohnson** [comment]
Thanks for: `Stripe::disableAmountConverter()`

**Comment by AidasK** [comment]
Refunds endpoint does not support currency parameter, so this amount converter just creates a bug. I think amount converter should be removed or disabled by default to avoid this odd behaviour. It just creates a potential bug for others.
