### ISSUE TITLE
Create customer

### ISSUE THREAD

**Issue by OneGerman** [cartalyst/stripe#167]
I want to create a customer while I'm charge the customer. 
But when I try to create the customer I get the error code: Invalid Object

`$customer = $stripe->customers()->create([
                'id' => auth()->user()->customer_id,
                'email' => auth()->user()->email,
                'shipping[address]' => auth()->user()->street,
                'shipping[name]' => auth()->user()->last_name,
                ]);`

Does anyone have a idea what I'm doing wrong ?

**Comment by Rhinoo3D** [comment]
I solved it myself.

If anyone want to know:

`'shipping[name]' => auth()->user()->first_name.' '.auth()->user()->last_name,
                'shipping[address][line1]' => auth()->user()->street,
                'shipping[address][city]' => auth()->user()->city,
                'shipping[address][state]' => auth()->user()->state,
                'shipping[address][postal_code]' => auth()->user()->zip,`

**Comment by brunogaspar** [comment]
Glad you solved it @Rhinoo3D 

The issue was that it was missing the `line1` inside the `address` array if i'm not mistaken.
