### ISSUE TITLE
Whats the proper way to deal with Webhooks?

### ISSUE THREAD

**Issue by nimabrownlee** [cartalyst/stripe#168]
Should you register a webhook endpoint and just use `Events`?

`$stripe->events()->all(['type' => ...]);`

Or should you just use a webhook signature verifier and do it the "normal" way?

**Comment by brunogaspar** [comment]
Hey

Validating the signature is the safest way to go about it, not only for Stripe but also for other types of webhooks you might receive, if those services offer that functionality of course.

**Comment by nimabrownlee** [comment]
@brunogaspar Ok thanks!
