### ISSUE TITLE
Error in documentation for Update a subscription

### ISSUE THREAD

**Issue by bertdida** [cartalyst/stripe#169]
I believe there's an error in `prorate` parameter description for [Update a subscription](https://cartalyst.com/manual/stripe/2.0#update-a-subscription) section.

The description says _The coupon unique identifier._ which doesn't make sense for a type of `boolean`.

**Comment by brunogaspar** [comment]
Feel free to submit a [pull request](https://help.github.com/articles/using-pull-requests/) :)
