### ISSUE TITLE
[Proposal] Ability to set the base URL for the API endpoint.

### ISSUE THREAD

**Issue by ChadSikorra** [cartalyst/stripe#172]
There are cases where being able to set the base URL (currently hard-coded in the Api class) could be helpful. For instance, setting it in order to use [stripe-mock](https://github.com/stripe/stripe-mock) for integration type testing.

I imagine setting it as an option in the Config class and defaulting it to its current hard-coded value.

**Comment by brunogaspar** [comment]
Hey

I haven't used Stripe Mock so i was not aware of such limitation here.

Don't see this being a bad thing to have implemented, therefore, if you're willing to implement some changes to allow this, please do go ahead :)
