### ISSUE TITLE
autocomplete / intellisense support?

### ISSUE THREAD

**Issue by jamesaspence** [cartalyst/stripe#173]
Any plans to help out w/ intellisense or autocomplete? It's kinda a bummer that I cannot type hint a stripe instance and be able to derive methods, return types, etc.

An example:
```
/** @var Stripe $stripe **/
$balance = $stripe->balance()->current();
```

Both `balance()` and `current()` will be unknown. On top of that, the return value of `current` is also unknown.

**Comment by brunogaspar** [comment]
Hey @jamesaspence 

Yes, this is something i'm planning to do for the upcoming version 3 release.

I don't have any immediate ETA at the moment to when that will be released though.

**Comment by brunogaspar** [comment]
Just created #186 which adds this for the upcoming 3 release.

It works as expected on VSCode, unsure about the other IDEs.

If you notice something might be missing or wrong, please do let me know.
