### ISSUE TITLE
Incompatible with Stripe's new Products API

### ISSUE THREAD

**Issue by thorlucas** [cartalyst/stripe#174]
This package seems to not work with Stripe's new products API and produces unexpected behavior.

For example, let's fetch all products.

With Stripe's new API from [stripe-php](https://github.com/stripe/stripe-php):

```php
$stripe = new Stripe\StripeClient('sk_test_xxxxx');
$stripe->products->all()

// returns
Stripe\Collection {#3034
     object: "list",
     data: [
       Stripe\Product {#3048
         +saveWithParent: false,
         id: "prod_xxxxx",
         object: "product",
         active: true,
         attributes: [],
         created: 1593399311,
         description: "My description",
         images: [],
         livemode: false,
         metadata: Stripe\StripeObject {#3054},
         name: "My name",
         statement_descriptor: null,
         type: "service",
         unit_label: null,
         updated: 1593399348,
       },
     ],
     has_more: false,
     url: "/v1/products",
   }
```

However, doing the same with Cartalyst Stripe (using the Laravel facade) returns nothing:

``` php
Stripe::products()->all();

// returns
[
     "object" => "list",
     "data" => [],
     "has_more" => false,
     "url" => "/v1/products",
   ]
```

However, fetching using `find` still works:

```php
Stripe::products()->find('prod_xxxxx')

// returns
[
     "id" => "prod_xxxxx",
     "object" => "product",
     "active" => true,
     "attributes" => [],
     "created" => 1593399311,
     "description" => "My description",
     "images" => [],
     "livemode" => false,
     "metadata" => [],
     "name" => "My name",
     "skus" => [
       "object" => "list",
       "data" => [],
       "has_more" => false,
       "total_count" => 0,
       "url" => "/v1/skus?product=prod_xxxxx&active=true",
     ],
     "statement_descriptor" => null,
     "type" => "service",
     "unit_label" => null,
     "updated" => 1593399348,
   ]
```

While it does return the product, it does not do so properly. It's still returning the `SKUs` which (I'm pretty sure) were deprecated with the `Orders` API.

**Comment by brunogaspar** [comment]
Feel free to submit a [pull request](https://help.github.com/articles/using-pull-requests/) :)

**Comment by brunogaspar** [comment]
Did a quick run on my end (with a production application), seems to work perfectly fine here

Tried with `2019-12-03` and the latest `2020-03-02` Stripe API version.

The unit tests seems to be passing as well, seems to be something on your end, please investigate.

**Comment by thorlucas** [comment]
@brunogaspar You're right. It appears what is actually happening is that Cartalyst stripe laravel claims that API key version is optional in the documentation. In my mind, this means that it will always use the latest version. However, it was instead using version `2017-06-05`. Perhaps this should be a separate issue, but I won't open one unless anybody else thinks that's problematic.

**Comment by GrahamCampbell** [comment]
The default API issue will be resolved in the next major version of this package (a solution is already implemented... basically, make the programmer specify instead of having a default that can't be bumped for BC reasons).
