### ISSUE TITLE
currency conversion issue 

### ISSUE THREAD

**Issue by amineameur** [cartalyst/stripe#175]
Hi,
first of all i want to thank you for this awesome package it's very helpful
i just have one  issue with changing the currency from USD to SAR
when i do the amount multiple *100 
so in case to charge a client for exemple 200 SAR it charges 20000 
i changes the return of the function convert and i return a simple $number without multiple it *100 but i got this error
Amount must convert to at least 50 cents. ر.س0.55 converts to approximately $0.14. 
what i can do to fix this problem 
thank you

**Comment by brunogaspar** [comment]
You can just disable the amount converter by calling `Stripe::disableAmountConverter()` somewhere on your code before doing the rest of the API calls, that way you should be able to have the value you want.

Hope it helps.

Regards

**Comment by amineameur** [comment]
hi brunogaspar 
i disable the amount converter and  i got this error " invalid intger : 55.00"

**Comment by brunogaspar** [comment]
Yes, you need to convert the amount to cents yourself now, that way you're responsible of doing such operation and you can ensure the amount you pass does not get modified in any way.

You can also find the list of supported currencies and their minimum and maximum charge amounts [here](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts)
