### ISSUE TITLE
Support for Stripe Checkout missing?

### ISSUE THREAD

**Issue by thorlucas** [cartalyst/stripe#178]
Hi,

It appears that support for Stripe's Checkout system is missing. That is, there's no way to create a [`Session` object.](https://stripe.com/docs/api/checkout/sessions) Or am I missing something?

Thanks,

**Comment by brunogaspar** [comment]
Just not documented.

```php
Stripe::checkout()->sessions()->create([
    'cancel_url' => 'http://example.com/cancel',
    'success_url' => 'http://example.com/success',
    'payment_method_types' => ['card'],
    'line_items' => [
        [
            'name' => 'T-shirt',
            'description' => 'Comfortable cotton t-shirt',
            'amount' => 1500,
            'currency' => 'usd',
            'quantity' => 2,
        ],
    ],
]);
```

Hope it helps.

**Comment by thorlucas** [comment]
Thanks! Funny enough, I discovered this a good 30 seconds before you commented this. I was browsing the source because I thought I would have to add it myself and submit a PR :)

**Comment by brunogaspar** [comment]
No problem, glad you figured it out before my reply :)

There's a chance stuff is missing and we welcome pull requests ;)

**Comment by IlCallo** [comment]
Note that `line_items` won't accept a Laravel Collection, throwing an obscure error (the item is removed from the params array because not recognized I guess)
