### ISSUE TITLE
Verifying webhook signatures

### ISSUE THREAD

**Issue by thorlucas** [cartalyst/stripe#179]
Hi,

I can't seem to figure out how to verify webhook signatures. From Stripe's docs:

```php
$endpoint_secret = 'whsec_...';

$payload = @file_get_contents('php://input');
$sig_header = $_SERVER['HTTP_STRIPE_SIGNATURE'];
$event = null;

try {
    $event = \Stripe\Webhook::constructEvent(
        $payload, $sig_header, $endpoint_secret
    );
} 
```

So I would expect something like this:

```php
Stripe::webhook()->constructEvent(...)
```

I've looked in the source and can't seem to find the relevant function. Nor can I find a function for constructing an event object from posted parameters at all. Is this included in the library? Or should I [verify the signature manually](https://stripe.com/docs/webhooks/signatures)?

Thanks for this awesome library and all your help!

**Comment by brunogaspar** [comment]
We don't have any way to validate or verify the legitimacy of webhooks, since this is just an API client, so you would have to build such thing yourself for now.

But can be considered to be added.

**Comment by GrahamCampbell** [comment]
Something you can do if you don't wanna bother validating webhooks is just to ignore the request body apart from the event ID, and then lookup the event ID on stripe, and use that data. If you also keep a record of which events you have processed already, then your code is safe from injection of invalid events and also from replay attacks.

**Comment by thorlucas** [comment]
@brunogaspar Thanks! However, the Stripe API provides a method to do this by providing the payload, the signature, and the endpoint secret. I assume their library does the manual verification steps which essentially only involves concatenating the data and computing an HMAC. So I'm not sure what you mean by this is just an API client.

I would submit a PR but I'm not an experienced PHP developer so I don't feel quite comfortable working on security related things. 

@GrahamCampbell I could do that, but Stripe recommends that their webhooks should get a 200 response ASAP, otherwise this slows down the checkout process for the end user.

**Comment by GrahamCampbell** [comment]
> 200 response ASAP, otherwise this slows down the checkout process for the end user.

That isn't true. It doesn't matter what response code your server returns, even an error, or if it blocks for ages and stripe gives up and closes the connection. What they might be referring to is that if your server acts in such a way that the stripe webhooks are the authority for which plan a user is subscribed to, etc, then there will be a delay if you are slow to process the webhooks. Sending out an HTTP request to get the event data won't slow you down in any noticeable way unless your network is terrible (but then you must have been slow to receive the request anyway). Also, note that Stripe will retry failed hooks (I think for up to 48 hours, or something of that order).

**Comment by GrahamCampbell** [comment]
Stripe itself certainly doesn't block waiting for your server to respond to a hook.

**Comment by brunogaspar** [comment]
I prefer to not add extra stuff that does not really exist on the Stripe API spec.

There's different ways to perform such check anyway.

Thanks!
