### ISSUE TITLE
Retrieve all customers - more than 10?

### ISSUE THREAD

**Issue by rtfmfm** [cartalyst/stripe#192]
Hello!
In the package documentation is written that we can retrieve all customers with: `$customers = $stripe->customers()->all();`
but this retrieves the default value of 10. As per stripe documentation, we can retrieve between 1 and 100 customers. Is this possible with this package?

**Comment by brunogaspar** [comment]
Yes, pass an array as the first and single parameter on the `all()` method and inside the array you can set the limit you want:

```php
$stripe->customers()->all(['limit' => 50]);
```

The list of arguments you can pass inside the array is defined here https://cartalyst.com/manual/stripe/2.0#retrieve-all-customers

Hope it helps!

**Comment by rtfmfm** [comment]
Thank you!
