### ISSUE TITLE
Cartalyst\Stripe\AmountConverter is not working

### ISSUE THREAD

**Issue by surtibhavin6006** [cartalyst/stripe#193]
I have given a amount as 3.26 while creating a plan and returning as 326.
Same as on given amount as 5.00 returns 500.

However, at stripe it is storing 3.26 or 5.00 but response is not getting perfect.

**Comment by GrahamCampbell** [comment]
> I have given a amount as 3.26 while creating a plan and returning as 326.

That is correct. Stripe uses integers and stores currency in cents.

**Comment by surtibhavin6006** [comment]
https://cartalyst.com/manual/stripe/2.0#plans
Here in example , if I pass 5.00,it it give create a plan on stripe with 5.00 ,but return 500 in array response.

**Comment by surtibhavin6006** [comment]
okay got it. sry for misunderstanding.
