### ISSUE TITLE
Get balance for connect accounts

### ISSUE THREAD

**Issue by dominik-wbz** [cartalyst/stripe#198]
As you can see in example https://stripe.com/docs/connect/account-balances you can pass 
`['stripe_account' => '{{CONNECTED_STRIPE_ACCOUNT_ID}}'];` to Balance::retrieve

Your Balance model doesn't exceptr any parametrs, how would you get the balance of a connected account?

Thank you,

**Comment by brunogaspar** [comment]
Hello @dominik-wbz 

If i remember correctly, you should be able to do:

```php
Stripe::setAccountId('{{CONNECTED_STRIPE_ACCOUNT_ID}}')->balance()->current();
```

I have not tested it with a connected account, but the `setAccountId()` method is to set the connected account you want to interact with.

**Comment by dominik-wbz** [comment]
Thank you @brunogaspar I was able to make it work in laravel using

`Stripe::accountId('{{CONNECTED_STRIPE_ACCOUNT_ID}}')->balance()->current()`

**Comment by brunogaspar** [comment]
No problem, glad you got it working :)
