### ISSUE TITLE
Missing functionality: Mandates

### ISSUE THREAD

**Issue by alexander-rieder** [cartalyst/stripe#199]
Hello Everyone,

i really like this package, but i noticed that it lacks the functionality to retrieve mandates from stripe.
https://stripe.com/docs/api/mandates

Am I missing something or is it not yet implemented?

Thanks in advance,
Alex

**Comment by brunogaspar** [comment]
Hello

This is missing at the moment, but you're more than welcome to send a pull request implementing it, since it seems quite simple to do (just a single endpoint, from their API docs) :)

**Comment by alexander-rieder** [comment]
that is my first pull request... so be easy with me :)

**Comment by brunogaspar** [comment]
It looked pretty good, thanks!

Will release v2.4.4 in a bit :)
