### ISSUE TITLE
Charges All with date paramaters

### ISSUE THREAD

**Issue by s7thamon** [cartalyst/stripe#201]
How would you correctly specify the `starting_after` and `ending_before` parameters in charges()->all ?

```
$date = \Carbon\Carbon::today();

$stripe = \Stripe::charges()->all([
  'starting_after' => $date->startOfDay(),
  'ending_before' => $date->endOfDay(), 
]);

```

No matter what I attempt for these, they always return the same number of records which is incorrect for my data set. I did try converting them to stripe's requirement for timestamp but it appears this package may take care of that for you?

**Comment by brunogaspar** [comment]
Hi,

If i remember correctly, both should use a charge id (object id), not dates, but i might be wrong.

You can check their official API docs for the proper parameters list https://stripe.com/docs/api/charges/list

**Comment by s7thamon** [comment]
Read the docs wrong and missed those params were for pagination.

```
Stripe::charges()->all([
  'limit' => 50,
  'created' => [
    'gte' => $date->startOfDay()->timestamp,
    'lte' => $date->endOfDay()->timestamp
  ]
]);
```
