### ISSUE TITLE
[docs] Replace "Cancel a payment intent" to "Capture a payment intent"

### ISSUE THREAD

**Issue by kirkcharlesniv** [cartalyst/stripe#205]
https://cartalyst.com/manual/stripe/2.0#cancel-a-payment-intent-2

![Screen Shot 2021-06-01 at 8 14 04 PM](https://user-images.githubusercontent.com/19856377/120321463-eb0a9180-c315-11eb-8497-e859fe235e7d.png)

**Comment by brunogaspar** [comment]
Should be addressed, thanks for the heads up.
