### ISSUE TITLE
Feat: Pager should be implemented with generators

### ISSUE THREAD

**Issue by AidasK** [cartalyst/stripe#206]
Currently pager loads entire dataset in memory which is not always possible when you have millions of records. To fix this pager should be implemented with generators.

https://github.com/cartalyst/stripe/blob/v2.2.0/src/Pager.php#L58

**Comment by brunogaspar** [comment]
Hey

That's the current expected behaviour, however, as your business grows, the amount of data could be very large, so it it would be nice to have such feature.

Feel free to submit a pull request that does not break the current implementation, even if it's a new method :)
