### ISSUE TITLE
Making refunds using payment intent id

### ISSUE THREAD

**Issue by ZejdCicak** [cartalyst/stripe#207]
Can someone please tell me if this is possible since by looking at Stripe API references it says : 
`To refund a payment using the API, create a Refund and provide the ID of the charge or PaymentIntent to be refunded.`

But I can't seem to find an option to do it with this package, and providing payment intent id in 
`$stripe->refunds()->create();`
Throws an error on Stripe saying that it can't locate a charge with that ID.

Is this hardcoded to use charge in the library and is there any workaround?

**Comment by ZejdCicak** [comment]
Managed to solve this by getting a payment intent and then accessing a charge id from charges array, but I still believe there should be an option to send payment intent id while making a refund.

I have checked your 3.x-dev branch and there too you didn't specify payment intent id in parameters, but again only charge id.

**Comment by brunogaspar** [comment]
Hey!

The refunds implementation was done around **charges** (when there was only charges and nothing else), however, i think we can make that method to determine if the provided ID is for a Charge or for a Payment Intent, since Stripe prefixes the ID's in a "predictable" way i think we are able to achieve that. Unless there's other alternatives?

@ZejdCicak Do you want to submit a pull request with some tests (there are quite a few examples for this)?

**Comment by ZejdCicak** [comment]
I will take a look at it tomorrow, a bit more around your dev codebase to see how you have done things in the past, and if I feel confident enough to make a pull request, since I have never done that on an open source project, I will let you know if that is ok with you.  

On which branch do you want the PR to be made? 3.x or 2.4?

**Comment by brunogaspar** [comment]
> I will take a look at it tomorrow, a bit more around your dev codebase to see how you have done things in the past, and if I feel confident enough to make a pull request, since I have never done that on an open source project, I will let you know if that is ok with you.

It's all good, that's why there's code reviews :)

> On which branch do you want the PR to be made? 3.x or 2.4?

Please send to 2.4 branch.

Thank you!

**Comment by ZejdCicak** [comment]
I have opened a pull request so see if that is good enough.

**Comment by ZejdCicak** [comment]
Any idea when you might tag this so I can use just composer update to get it?
Also if i got it right this will reflect in the stripe-laravel as well right, since that is only a Facade for laravel?

**Comment by brunogaspar** [comment]
> Any idea when you might tag this so I can use just composer update to get it?

I need to address some failing tests before tagging, so it might take a bit more time to take care of them.

> Also if i got it right this will reflect in the stripe-laravel as well right, since that is only a Facade for laravel?

Yes, that's correct.

**Comment by brunogaspar** [comment]
Released v2.4.6

Thank you for the pull request @ZejdCicak !
