### ISSUE TITLE
Creating Plan is not working

### ISSUE THREAD

**Issue by ridetothefuture** [cartalyst/stripe#210]
Hello,  first of all, I want to say thanks for creating this amazing PHP package for stripe. 

While using this package I found below 2 errors:

1) I tried to create a plan like this but I got an error. The error was related to the name attribute we're passing to the function while creating the plan.  Below is the exact error.

```
Cartalyst\Stripe\Exception\MissingParameterException
Received unknown parameter: name
```

2) After removing the name from the attributes array, I faced another issue that was related to the product. The product is the required parameter that we need to pass in order to create the plan. Below is the exact error.

```
Cartalyst\Stripe\Exception\MissingParameterException
Missing required parameter: product
```

This is how the stripe create plan API works: https://stripe.com/docs/api/plans/create

Thanks

**Comment by suwardany** [comment]
Hi,

You are referencing the official stripe api docs, the documentation for this package can be found at https://cartalyst.com/manual/stripe/2.0

Hope that helps!
