### ISSUE TITLE
Allow refunds using py_ payment token

### ISSUE THREAD

**Issue by francoisburdy** [cartalyst/stripe#216]
Hey!

Since 2.4.6, it is possible to make refunds from Payment Intents (pi_) tokens, while the previous version only allowed to use charges tokens, which is great.

However it seems there is a downside in the new implementation that makes impossible to create a refund using a py_ token even though the Stripe API allows it and treat it as a charge token.

In my case, I use Sepa Debits and the API gives me a py_ token only. I found no way to get a ch_ or pi_ token associated to the payment.

If I try to pass a py_ token to the Refund->create() method (which I got working for long) , now I get an a `No such payment_intent: 'py_[...]'` error.

For now I manage to make refund bypassing the Refund->create() method, this way  : 

```php
$stripe->refunds()->_post('refunds', [
    'amount' => $amount,
    'charge' => $my_py_token,
]);
```

A solution can be to invert the ternary mentioned below, to use the charge mode by default, and the PaymentIntent only if `$paymentId` is a pi_ token ?

https://github.com/cartalyst/stripe/blob/482671a0c24133244fcb8e1da06e108c7efb610b/src/Api/Refunds.php#L103

Many thanks! and long live this package!

**Comment by brunogaspar** [comment]
So `ch_` and `py_` are for charges? Do you know if there's any other prefixes?

I don't mind having it switched around, as long as everything passes :)

You up for doing a pull request?

Thank you!

**Comment by francoisburdy** [comment]
No idea if there are other prefixes that can be used, as the stripe documentation is not extensive on this topic.

All I can say is that according to my tests, the post refund endpoint behaves the same with py_ and ch_ tokens :)

See my pull request https://github.com/cartalyst/stripe/pull/217
