### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sdeering** [cartalyst/stripe#23]
Hi guys, is there a pagination example anywhere? The docs are inconclusive about it.

Just below this section it states you can use this to create pagination.

```
Stripe::customersIterator()
```

Doesn't state: a) how many is in the page b) which page your on c) how to query a specific pages?

https://cartalyst.com/manual/stripe/1.0#usage-2

**Comment by brunogaspar** [comment]
Hello,

The iterator is not supposed to work like that, it's supposed to only return all the results from Stripe on one go, if you need real pagination, you need to store these on your database and paginate yourself.

**Comment by sdeering** [comment]
Ok I understood. So can you explain the purpose of the interator if it just
returns the same as all()?

**Comment by GrahamCampbell** [comment]
> if it just returns the same as all()?

No... That's not the same. An iterator could allow you to traverse a large amount of data without having to actually load it all into memory at once. You can load chunks at a time, while keeping a bog standard foreach, or whatever.

**Comment by sdeering** [comment]
Ok thanks for explaining if you get the time maybe add something quick as
an example code to the docs. It would greatly help those who have a large
data set. I might be looking at around 3-5,000 subscriptions.

**Comment by brunogaspar** [comment]
@sdeering Not sure if you're using Laravel, but if you're, you can use the Laravel Paginator for this, you can have for example a cron job where you call the iterator and you cache the response, like, hourly, then you use the Laravel Paginator to have the results paginated, one easy solution.

Other solution would be to store the results on your database, as i mentioned, this way you can easily paginate them too.

Either way, it's more faster than querying Stripe each time you change page, i personally prefer to store the data on the database, as it's more easier to do look ups if required, but, what you want is still possible at the API level, if you know how of course, you can use the `all()` method and pass the `starting_after` and `ending_at` parameters as it's documented on the [Stripe API](https://stripe.com/docs/api#list_customers) which will allow you to have this "pagination" effect in the end.

Since this is out of the scope of the package or the documentation itself, i don't really feel we need any examples on the documentation for this kind of stuff, sorry.

**Comment by sdeering** [comment]
Thanks Bruno that is fantastic advice. I have the ability to code any one
of the 3 examples you mentioned and will go as you suggested and store
results in the database and have the cron (Larevel 5 subscriber) tasks help
keep the data up to date. With also probably an admin function to manually
refresh. I will follow up with a blog post if I have some spare time to
share knowledge with others. Thanks again. Sam

**Comment by sdeering** [comment]
Hi,

Samuel Lee Deering invited you to LinkedIn.
Join now to connect with Samuel Lee and the rest of your professional world.

Confirm that you know Samuel Lee: https://www.linkedin.com/e/v2?e=-lwd3ny-igwz479i-d&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=hGuvaUwe&invitationId=6070740670564360192








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-lwd3ny-igwz479i-d&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGgaBhieGFKBgAAAVD-alNLcvG7NJkHdbRvX7DGufLcF_9L_bUNIppFjWlv0Ivu6C5gwrq8vcu3eY3ciOovJD_0Iiw9p3PZuV51g2cd_GzAyrieHu1JJBH68Mumnb9KV6gLsNZu3fIWud0rk4ilP7j1TiQoeXjnJDmFk-72zUOxp5a2ycxhGp16Yqjf6LjitPyN&eid=-lwd3ny-igwz479i-d


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-lwd3ny-igwz479i-d&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Hi cartalyst/stripe,

I&#39;d like to include you in my network to share updates and stay in touch.

- Samuel Lee

Confirm that you know Samuel Lee: https://www.linkedin.com/e/v2?e=0-igwz4imy-69&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=jFlNoRXd&invitationId=6070740670816010240








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-igwz4imy-69&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGWl636I3NDvAAAAVD-an37iKibStT9f7uVfHLQr4bllMZpeJdv3Xu2EBP5jM93tfHoGBw21Dde4sLnHECRTJM7rPRU78ptsPWpQ6wxq4F8zwALGmSZJ-2AqgoDBCVJHLbX8I9qfi-FjyaPdPhNwoh9CpAFQCuXHRuopqWMyI994sOcB1Qj6TNVxmG5XHRoma96&eid=0-igwz4imy-69


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-igwz4imy-69&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Hi cartalyst/stripe,

I&#39;d like to include you in my network to share updates and stay in touch.

- Samuel Lee

Confirm that you know Samuel Lee: https://www.linkedin.com/e/v2?e=0-igwz4iis-6h&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=stVRR032&invitationId=6070740676436377600








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-igwz4iis-6h&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGdS3pKYLYUfwAAAVD-an4f55y0Wq5oTxdSaCgERqKr_CKPF3ALpxxt6CwRnJag10tvPnd3i6zE43KsCnbYvhhEW-7phk-j1iVHblfDWaF4ybdDRjgyLTJwHsRHyW1iawI4cMnKGJyx1wORZJqLnCw-kD0i9Nsf8FnSiXOBbtvs95EszaWOY_EwUduehvFGqLqL&eid=0-igwz4iis-6h


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-igwz4iis-6h&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-lwd3ny-ih59j6wi-5t&a=preRegInvite&ek=first_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=hGuvaUwe&invitationID=6070740670564360192

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/comm/profile/view?id=AAsAAARlPb8BK5W5e50abjDagJEHAwJ90SAVRs4&trk=eml-first_guest_reminder_01-hero-14-profile_text&trkEmail=eml-first_guest_reminder_01-hero-14-profile_text-null-%7Elwd3ny%7Eih59j6wi%7E5t





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-lwd3ny-ih59j6wi-5t&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-lwd3ny-ih59j6wi-5t&loid=AQGpEZAmB1T9QQAAAVEdeWVXlxUFIvmsSXQiNFO6ncUGfHytKoAzektdXQQ4N9xJM1vaVkTGO3j_grmZcN5R1thy-W8gTieur_s_cq0mPu2acJWa-LND1HpqPjmfkcDTYymoAG4lpExBTAn3AitiGq75AZtLNvrAM0tw8AJxzStJ02gTe2L9UOfg-0fkrX1iq58e

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-lwd3ny-ih59j6wi-5t&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-2oe84b-ih59j4f6-69&a=preRegInvite&ek=first_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=jFlNoRXd&invitationID=6070740670816010240

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/comm/profile/view?id=AAsAAARlPb8BK5W5e50abjDagJEHAwJ90SAVRs4&trk=eml-first_guest_reminder_01-hero-14-profile_text&trkEmail=eml-first_guest_reminder_01-hero-14-profile_text-null-%7E2oe84b%7Eih59j4f6%7E69





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-2oe84b-ih59j4f6-69&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-2oe84b-ih59j4f6-69&loid=AQFESTxPaMrujwAAAVEdeXkvgDyQAbjAjm516MaYVGcKoASrQ2NwPVNxQYJbjJN7JwU1flsQw_D9YOwfPVoIm9XcRDcO6jSJ_7tPN5R2wd6afeuX5p7X0uivtBWgIrP4iyptO9PHCe9WoOaR7S589s7mLfJpw_PQu8d-ELCq2MnC-yPipUdLDkrVZLeRt5uj0pCr

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-2oe84b-ih59j4f6-69&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-mctmzj-ih59ipl7-2f&a=preRegInvite&ek=first_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=stVRR032&invitationID=6070740676436377600

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/comm/profile/view?id=AAsAAARlPb8BK5W5e50abjDagJEHAwJ90SAVRs4&trk=eml-first_guest_reminder_01-hero-14-profile_text&trkEmail=eml-first_guest_reminder_01-hero-14-profile_text-null-%7Emctmzj%7Eih59ipl7%7E2f





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-mctmzj-ih59ipl7-2f&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-mctmzj-ih59ipl7-2f&loid=AQE9-QMwnhHvIQAAAVEdeg_K6OuJNMfuJJPuwQEzOP4hetMM0sVfqJNhftv7Ej5RYtvg380XD80kQb1VydjTEDiAPifV8-IDey9pG-QKb9IciUqBTc5u5Hsw8TdAbxoQ9tfkhytNGqusUgakxuC1INJOZk7Oz46wv4a13CxBb3xkleev07xUZgmpHpM0tDsS-Qhl

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-mctmzj-ih59ipl7-2f&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by brunogaspar** [comment]
@sdeering Why your GitHub username is doing this type of spam comments? Please check it.

**Comment by ninjaparade** [comment]
@brunogaspar think he really wants to connect with you on github :shit: :goat:

**Comment by brunogaspar** [comment]
It's from Linkedin, and this is not Brosbook, it's GitHub :trollface:

**Comment by ninjaparade** [comment]
@brunogaspar just accept his invite and grow your personal network :+1:

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-lwd3ny-iheb5wti-4d&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=hGuvaUwe&invitationID=6070740670564360192

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/e/v2?e=-lwd3ny-iheb5wti-4d&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=hGuvaUwe&invitationID=6070740670564360192





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-lwd3ny-iheb5wti-4d&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-lwd3ny-iheb5wti-4d&loid=AQGPxl6esofdLAAAAVE9q1BUzCTNcr42XjJXZilYx6wpLlEzj8dO9tXSLQSXz-tASgWvc9bL9JqKthiKXeH18Pv3wzcY05OEep-PJWBTUhlO_TwHp5XHHmX8jbUlzCGO-Z5nwtu_Yb39FB8Km_XEpSPMR0qzjEx8Z26rp2axdBwzxvYMUH31AZ1gDVdOWaqbbn_V

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-lwd3ny-iheb5wti-4d&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-mctmzj-iheb34ti-5&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=stVRR032&invitationID=6070740676436377600

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/e/v2?e=-mctmzj-iheb34ti-5&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=stVRR032&invitationID=6070740676436377600





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-mctmzj-iheb34ti-5&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-mctmzj-iheb34ti-5&loid=AQHQTgLkHMwYVgAAAVE9rLl-FIQQMy2bU84A9Dincpt7PMsCM-64bztkU4rtO38G8K04ZrCFpXmNJ8YsjJuRb18ksvq-kdgJz-IA1m1QVYg7PuyyikVnDSfRLjYDpNn6L1Xd7ml4FeO-SCehQDZ43k1ujHcTgN1MWr6hQVnaD0XeGyMBJWYAnp-nM59T4LdUhWUc

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-mctmzj-iheb34ti-5&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-2oe84b-iheb5wth-2z&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=jFlNoRXd&invitationID=6070740670816010240

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/e/v2?e=-2oe84b-iheb5wth-2z&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=jFlNoRXd&invitationID=6070740670816010240





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-2oe84b-iheb5wth-2z&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-2oe84b-iheb5wth-2z&loid=AQEw0NKqL2Gb3wAAAVE9rTuzjbmS251j_b0rkyUbd_SQnDOPTquHLSx7wqFlpbrOI3fQCLqZOWJaETNzHXG9uYi5rYkXJS8wkM6_lD1YuOA_w3v4yX3CVLFLc8FrI0qs8EbI8gbRT1AqOmiNDiBQ-RyYx0HBeJXnAnGfqfxYBdnSuj4MR17EK8h3jR4z0jY3YSfu

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-2oe84b-iheb5wth-2z&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
