### ISSUE TITLE
Missing Managed Account Functionality

### ISSUE THREAD

**Issue by monove** [cartalyst/stripe#24]
In the Stripe API, there are multiple calls related to Managed Accounts (ie https://stripe.com/docs/api#create_account).

Any ETA on when this will be implemented by Cartalyst?

**Comment by brunogaspar** [comment]
Hello,

There's no ETA, you can send a PR if you want.

**Comment by monove** [comment]
I am not familiar enough with the PR flow to know what to do.
I forked this repo and made changes here: https://github.com/monove/stripe/blob/1.0/src/Api/Account.php
I tested all these calls and they work flawlessly.
Would you consider merging this is?

**Comment by brunogaspar** [comment]
Of course, submit the PR to the `1.0` branch =)

**Comment by monove** [comment]
https://github.com/cartalyst/stripe/pull/25/
