### ISSUE TITLE
[Proposal] Create customer's recurring profile along with credit card details and subscription plan

### ISSUE THREAD

**Issue by devendragohil** [cartalyst/stripe#26]
As per Stripe document https://stripe.com/docs/subscriptions#subscribing-a-customer-to-a-plan , if I provide the credit card details and plan while creating a new customer, the card will be charged immediately and will return the response once done. My project requirement is the same. I want to subscribe the customer to a recurring plan while creating him and also want the first payment must be done immediately that I may mark him as verified and he should be able to login to my system. 

Is it possible using your package?

**Comment by brunogaspar** [comment]
You can either:
- [Attach a card](https://cartalyst.com/manual/stripe/1.0#cards) to a customer without charging him and then you create a subscription. 
- When you're creating a subscription you provide the card, either a Stripe Token or an array (check the previous link to see how you should populate the array with the key/value pairs).

You can read more about how to create subscriptions [here](https://cartalyst.com/manual/stripe/1.0#create-a-subscription).

I recommend the usage of the Token provided by the Stripe.js plugin, this is more secure.
