### ISSUE TITLE
WAMP -  GuzzleHttp \ Exception \ RequestException  cURL error 60: SSL certificate problem 

### ISSUE THREAD

**Issue by devendragohil** [cartalyst/stripe#27]
I am using WAMP 2.5 with PHP 5.5.12 and Apache 2.4.9 with Windows 8.1.

I am working on Laravel 4.2 project and recently I've installed this package using composer. I am trying to create token using your package's sample code https://cartalyst.com/manual/stripe/1.0#tokens , with localhost. The sample code is as below :

$stripe = new Stripe;
$stripe = Stripe::make('my-stripe-test-public-key');

$token = $stripe->tokens()->create([
	'card' => [
		'number'    => '4012888888881881',
		'exp_month' => '05',
		'cvc'       => '123',
		'exp_year'  => '2016'
	],
]);

But I'm getting this error : 

GuzzleHttp \ Exception \ RequestException

cURL error 60: SSL certificate problem: unable to get local issuer certificate

I've tried different solutions like setting 
curl.cainfo="<path-to>cacert.pem" in php.ini also used ca-bundle.crt with the same, restarted WAMP many times but any solution is not working. 

I've open_ssl module and cURL enabled in php as well as in apache. Can you please provide me any solution??

**Comment by brunogaspar** [comment]
It's an issue on your environment, have a read here https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate there are quite a few suggestions for your problem.
