### ISSUE TITLE
Iterator For Pagination

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#30]
Would it not be better to return an iterator for the pagination instead of trying to load everything into memory, which will end in a mess for very large data sets.

**Comment by brunogaspar** [comment]
Probably on the next version, but if you want to send a PR that keeps the current behaviour, go for it.

**Comment by GrahamCampbell** [comment]
Sure. I'm a bit busy now, so ping me in a few days if I forget to do this. :)

**Comment by brunogaspar** [comment]
Ok, i'll leave it open.

**Comment by phroggyy** [comment]
@GrahamCampbell stumbled across this issue by chance, is this anything you've had any time to think about?

**Comment by GrahamCampbell** [comment]
I'll see if I can fit this in next week. :)

**Comment by brunogaspar** [comment]
Is this still something you might want to have a look @GrahamCampbell ?

Probably a good opportunity for 3.0.
