### ISSUE TITLE
Guzzle 6 Support

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#31]
Is guzzle 6 support planned?

**Comment by brunogaspar** [comment]
Not at the moment, Guzzle 5 works fine.

**Comment by GrahamCampbell** [comment]
Ok, it's just that Laravel 5.2 doesn't support guzzle 5 so people wanting to use this package in the future along side laravel's mail component for example will run into bother.

**Comment by GrahamCampbell** [comment]
Guzzle 5 support in laravel 5.1 is already deprecated.

**Comment by brunogaspar** [comment]
When L5.2 gets released we'll worry about supporting it, at the moment, i'm not worried or even concerned.

**Comment by GrahamCampbell** [comment]
Ok, sure. I was just thinking ahead. :)

**Comment by GrahamCampbell** [comment]
Any movement here?

**Comment by brunogaspar** [comment]
I've been quite busy, so no.

**Comment by GrahamCampbell** [comment]
Ok. ;)
