### ISSUE TITLE
BindingResolutionException

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#34]
Target [Cartalyst\Stripe\ConfigInterface] is not instantiable

Get this exception when using your laravel package. The interface is never bound to a concretion?

**Comment by brunogaspar** [comment]
Can't reproduce.

**Comment by GrahamCampbell** [comment]
I'll send a PR to the laravel pacakge. Had time to sleep on it and I'm pretty sure I know why this isn't working now.

**Comment by GrahamCampbell** [comment]
See https://github.com/cartalyst/stripe-laravel/pull/3.

**Comment by brunogaspar** [comment]
Still, this doesn't really explain why it's giving that error.

You haven't showed me how to reproduce your error either.

I have it working fine on a 4.2 application and it's successfully working on 5.1 as well which was recently upgraded from 5.0.

**Comment by GrahamCampbell** [comment]
Oh right, it happens when I try to dependency inject any of the classes in the API namespace.

**Comment by brunogaspar** [comment]
Seems weird, why are you doing that?

**Comment by GrahamCampbell** [comment]
Well, because that's the object I want?

**Comment by brunogaspar** [comment]
Ok i see.

Send to 1.0 instead please, i'll merge it back to 2.0 after.

**Comment by GrahamCampbell** [comment]
Ok. :)

**Comment by GrahamCampbell** [comment]
See https://github.com/cartalyst/stripe-laravel/pull/4.
