### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by canfiax** [cartalyst/stripe#36]
I am about to integrate Stripe Connect in my Laravel 5.1 project.

 - Does this package support Stripe Connect?
 - Is there any documentation on how to implement (i.e. connecting users on a standalone account https://stripe.com/docs/connect/standalone-accounts#connecting-users).

**Comment by brunogaspar** [comment]
You will need to create a new instance of the package (its on the documentation) and instead of your API Key you set the API Key of the connect account.

The API to interact is the same so everything should work as it normally would.

**Comment by sdeering** [comment]
Something like this?

```
	/**
	 * Changes the account your connected to on Stripe.
	 */
	public function changeAccount($id) {
		$this->stripe = Stripe::make(env($id.'_SECRET_KEY'), env($id.'_API_VERSION'));
	}
```

with say $id = STRIPE2 and .env settings:
```
#WELU SPECIALISTS STRIPE
STRIPE2_SECRET_KEY=sk_test_FeQgIxYqC...
STRIPE2_PUBLISH_KEY=pk_test_5uAxUr3LU...
STRIPE2_API_VERSION=2015-02-18
STRIPE2_CLIENT_ID=ca_6yjkhH47CuiKHKeh...
STRIPE2_CALLBACK=http://domain.com/stripeCallback
```

**Comment by brunogaspar** [comment]
That should do it, yes.
