### ISSUE TITLE
Create account

### ISSUE THREAD

**Issue by canfiax** [cartalyst/stripe#37]
How do you create an account?

I need to use Stripe Connect, and create an account on behalf of the user.

**Comment by canfiax** [comment]
Like so: https://stripe.com/docs/connect/deferred-accounts#creating-a-standalone-account

**Comment by brunogaspar** [comment]
Its not documented but you can call account()->create($parameters);

**Comment by canfiax** [comment]
Thanks. I just noticed when creating an account, and the account e-mail is already taken, a `Cartalyst \ Stripe \ Exception \ MissingParameterException (400)` exception is thrown. Is this a bug?

**Comment by brunogaspar** [comment]
Not sure, seems to work here.

How're you doing the call?

**Comment by canfiax** [comment]
Well, the call works fine, but the exception it throws is not very helpful.

Currently, to find out if the error was that user email already exists, you have to do something like this:

	try {
		/**
		 * Create
		 * @var [type]
		 */
		
			$stripeAccount = \Stripe::account()->create([
				'country' => $this->getCountryCode(),
				'managed' => false,
				'email' => $this->email,
			]);

	} catch (\Cartalyst\Stripe\Exception\MissingParameterException $e) {
		switch ($e->getMessage()) {
			case 'An account with this email already exists.':
				/**
				 * Account already exists
				 */
			break;
		}
	}

**Comment by brunogaspar** [comment]
Ok, will have a look into improving the exceptions.

**Comment by canfiax** [comment]
+1
