### ISSUE TITLE
Is it possible to charge a specific users card?

### ISSUE THREAD

**Issue by murrion** [cartalyst/stripe#39]
I've started to use the Library with Laravel 5.1, its very good and it's helped me a lot.

Once thing I can't see in the code or documentation is how to charge a specific users card. Is this possible to do?

**Comment by brunogaspar** [comment]
Yes, you should be able to pass the `source` which is the card id that belongs to a customer when creating a charge. You need to pass the customer and the card (source) id.

https://cartalyst.com/manual/stripe/1.0#create-a-charge see the allowed parameters here.

**Comment by murrion** [comment]
Perfect, I tried it and it worked well, thank you.

**Comment by brunogaspar** [comment]
Awesome :+1:
