### ISSUE TITLE
quick questions regarding stripe connect

### ISSUE THREAD

**Issue by sdeering** [cartalyst/stripe#40]
Hi cartalyst,

Does this support Stripe Connect?
https://stripe.com/docs/connect/migrating

Which API version is supported?
I am using 2015-04-07 and wonder if anything will break if I upgrade?
```You're upgrading to the latest API version from 2015-04-07.```

As stripe documentation suggests:
```To start using managed accounts you must first activate your account as a platform. You must also be on at least version “2014-12-17” of the API. If you’re on an older version, please upgrade before migrating to managed accounts.```

```Why would you want to migrate? Recipients will be deprecated by the end of 2015—we will not break any existing integrations, but we won’t be documenting or maintaining it anymore. Secondly, the new APIs come with a lot of new functionality. If you’ve ever found yourself wishing that recipients worked better (e.g. tax reporting, improved identity verification), you might want to check out the new APIs.```

Would love to hear your thoughts on this guys. Let me know if I can assist in any way.

Sam

**Comment by brunogaspar** [comment]
> Does this support Stripe Connect?
https://stripe.com/docs/connect/migrating

Already answered here https://github.com/cartalyst/stripe/issues/36

> Which API version is supported?

Should work with all versions, unless there's new endpoints that haven't been implemented.

**Comment by sdeering** [comment]
Thanks mate, will report back if I find anything else.

**Comment by brunogaspar** [comment]
No problem :+1: 

Let me know if you have further questions or if you find any issues with the package.

**Comment by commandantp** [comment]
@sdeering did you implement it with Stripe Connect ? 
Any tutorial you found useful for that? 
Thanks!

**Comment by brunogaspar** [comment]
@commandantp Do you have any questions or issues?

**Comment by commandantp** [comment]
Basically I am reading through to understand how to deal with it. Have not been able to find a full example yet for the Stripe Connect. Just overall slightly confused on how/where to start but that's normal I guess...
Thinking of using the stripe-billing-laravel/3.0 package.

A/ What I think I got so far for Payment:
1- Include stripe js part in front-end 
2- User fills for payment and stripe.js returns a token
3- Submit the stripe token to the backend 
4- Either charge the card now (or keep it for later?)
5- When charging set the amount_fee for the application & the connected_stripe account that will get the money.

B/ Regarding user creation of their Stripe account:
1- include the Oauth button for the user to create their account
2- Stripe returns the API key to their account back
3- We store the key in our DB 
4- We use this key when paying out to this user as the connected_account receiver.

C/ From issue #36 I understand that we can do more things on behalf of that connected_account with their API key thus the need to load another instance?

Does that sound correct?

**Comment by brunogaspar** [comment]
> A/ What I think I got so far for Payment:

The workflow seems correct. 
Keep in mind that nor we or Stripe enforces you to do it in a specific way, so you're free do it the way it better fits your application, so you can charge right way or mark it to be charged later (manually).

> B/ Regarding user creation of their Stripe account:

Seems also correct.

> C/ From issue #36 I understand that we can do more things on behalf of that connected_account with their API key thus the need to load another instance?

Yes. You'll need to create a different instance to interact with a connected account.

**Comment by commandantp** [comment]
Thanks bruno!
