### ISSUE TITLE
Please tag a new version for the AmountConverter changes

### ISSUE THREAD

**Issue by tomschlick** [cartalyst/stripe#42]
The current version (v1.0.3) has a critical bug in it in regards to transforming the amount float into the stripe integer. If you try using a number like `79.99` it transforms it into `7998` and sends that number to stripe.

You have already fixed this with the `AmountConverter` class but a new version hasn't been tagged yet so cartalyst/stripe-billing-laravel hasn't picked up the change yet.

**Comment by brunogaspar** [comment]
:+1: 

Give me a few.

**Comment by tomschlick** [comment]
Awesome thanks!

**Comment by brunogaspar** [comment]
Tagged.

**Comment by tomschlick** [comment]
You're awesome. Thanks for the speedy response!

**Comment by brunogaspar** [comment]
No worries and thanks for reminding to create a tag, i forgot about it.

Let me know if you find any issues.
