### ISSUE TITLE
manage accounts are not working

### ISSUE THREAD

**Issue by nareshmenlo** [cartalyst/stripe#47]
manage accounts are not working

**Comment by brunogaspar** [comment]
You'll need to be way more specific than that.

**Comment by nareshmenlo** [comment]
Yes thanks for update,
I would like to get total payouts for the each mananged account.
thanks in adavance

**Comment by brunogaspar** [comment]
You'll need to fetch the balance/balance history for each account.

Not much we can do, unless Stripe provides that data on each connected account.

All up to you to implement this.

**Comment by nareshmenlo** [comment]
thanks
