### ISSUE TITLE
Class 'Cartalyst\Stripe\Stripe' not found

### ISSUE THREAD

**Issue by sgilberg** [cartalyst/stripe#50]
Hi, forgive me if this is a Symfony2 issue or other, but I've been using cartalyst/stripe in a production application in Symfony2 quite successfully for several months and I'm suddenly having problems, even though I haven't made any changes in my source code. My composer.json specifies "cartalyst/stripe": "1.0.*@dev". After my last composer update, which included an update to this package (but not an update to the symfony framework), my application can no longer find the class Cartalyst\Stripe\Stripe. The exception language is 'Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Stripe" from namespace "Cartalyst\Stripe". Did you forget a "use" statement for another namespace?" at [redacted]/app/cache/prod/appProdProjectContainer.php line 449'.  All other vendor files seem to be loading fine, and I see a class called Stripe in namespace Cartalyst\Stripe in my cartalyst vendor directory. Any ideas of what might be going on here? I couldn't find any obvious changes in either the Stripe file or the composer.json for this repository that would trigger this issue, but maybe I'm missing something.

**Comment by brunogaspar** [comment]
Not really related to your issue, but we don't recommend to use `1.0.*@dev` as a dependency version but rather use `~1.0`.

In regards of the issue, the namespaces are correct, and the tests we have are passing so not really sure what's wrong on your side but try to do a `composer dump-autoload` to see if the autoload file get's refreshed, but other than that i'm not seeing or experiencing this issue, sorry.

**Comment by sgilberg** [comment]
Thanks @brunogaspar for the quick response! Changing it to ~1.0 seems to do the trick, for whatever reason.

**Comment by brunogaspar** [comment]
Interesting heh.

Glad it's working now :)
