### ISSUE TITLE
Catchable Fatal Error

### ISSUE THREAD

**Issue by richard-parnaby-king** [cartalyst/stripe#51]
I am attempting to create a customer and am getting the following message:

> Catchable fatal error: Argument 1 passed to Cartalyst\Stripe\Exception\Handler::__construct() must be an instance of GuzzleHttp\Exception\ClientException, instance of GuzzleHttp\Exception\RequestException given, called in C:\xampp\htdocs\vendor\cartalyst\stripe\src\Api\Api.php on line 156 and defined in C:\xampp\htdocs\vendor\cartalyst\stripe\src\Exception\Handler.php on line 73

My code is:

```
$apiKey = 'my_test_api_key';
$apiVersion = '2015-10-16';
$stripe = new Stripe($apiKey, $apiVersion);
$customer = $stripe->customers()->create([
    'email' => $email, //gapohabo@yahoo.com
    'description' => $name, //Selma Tucker
]);
```

**Comment by richard-parnaby-king** [comment]
Guzzle could not locate my ssl certificate. Fixing that stopped the above error.

**Comment by lmrgyv** [comment]
How you fixed this?

**Comment by richard-parnaby-king** [comment]
I had this issue on my localhost. The problem boiled down to not having an SSL certificate and not making the request from a https scheme. To resolve this, downloaded a .crt file from somewhere (I can't remember from where), then had to configure my localhost (I run xampp) to allow https connections by editing the http-ssl.conf file. Unfortunately I can't remember what exactly I changed.
I also had to alter my php.ini file to point to the .crt file, but again, I can't remember the line I added. I'll try to find the various links and line changes I made.

**Comment by lmrgyv** [comment]
i created new server.crt with [XAMP makecert ](http://robsnotebook.com/xampp-ssl-encrypt-passwords). Now i have https. But problem not closed for me. 

`FatalThrowableError in Handler.php line 73:
Type error: Argument 1 passed to Cartalyst\Stripe\Exception\Handler::__construct() must be an instance of GuzzleHttp\Exception\ClientException, instance of GuzzleHttp\Exception\RequestException given, called in D:\web_sites\site.loc\laravel\offerz_gyv\offerz\vendor\cartalyst\stripe\src\Api\Api.php on line 156`

![img-2016-02-14-13-23-50](https://cloud.githubusercontent.com/assets/17012163/13033444/e7a1bea2-d31e-11e5-84e8-6876989293e9.png)
![img-2016-02-14-13-24-03](https://cloud.githubusercontent.com/assets/17012163/13033446/eff0c878-d31e-11e5-88df-a0a5467661f9.png)

**Comment by richard-parnaby-king** [comment]
I download the following certificate as cacert.pem: http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt

I add the following line to my php.ini file: `curl.cainfo = "C:\xampp\cacert.pem"`

Finally, I added the following vhosts data to my apache/conf/extra/httpd-vhsots.conf file:


```
<VirtualHost *:443>
    DocumentRoot "C:\xampp\htdocs-projects\my-project\public"
    ServerName my-project.dev
		<Directory C:\xampp\htdocs-projects\my-project>
				AllowOverride All
				Require all granted
		</Directory>
    SSLEngine on
    SSLCertificateFile "conf/ssl.crt/server.crt"
    SSLCertificateKeyFile "conf/ssl.key/server.key"
</VirtualHost>
```

**Comment by lmrgyv** [comment]
It does not work for me, but I try esch((

**Comment by brunogaspar** [comment]
@lmrgyv If you can't figure out a solution, i would open an issue on Guzzle side as the issue with the certificate has nothing to do with the Stripe package.

--

https://github.com/cartalyst/stripe/issues/38

**Comment by lmrgyv** [comment]
@brunogaspar It would be nice.

**Comment by olaniyimoses** [comment]
please, the above solution did not work for me as well. is it because i'm using wamp and not xamp

**Comment by olaniyimoses** [comment]
please, the above solution did not work for me as well. is it because i'm using wamp and not xamp

**Comment by brunogaspar** [comment]
Try to raise the issue on Guzzle side, not much we can do here, sorry.
