### ISSUE TITLE
Manual transfer to own bank account

### ISSUE THREAD

**Issue by monove** [cartalyst/stripe#57]
I am trying to set recipient as `default_for_currency` as per https://stripe.com/docs/api#create_transfer-destination
```
\Stripe::transfers()->create([
				'amount'    => 26.39,
				'currency'  => 'CAD',
				'recipient' => 'default_for_currency',
			]);
```
and it is not working

**Comment by brunogaspar** [comment]
What's not working? Any error?

**Comment by monove** [comment]
```
Cartalyst\Stripe\Exception\MissingParameterException with message 'Transfers to Recipient objects are not supported in your country (CA); try transferring to another Stripe account instead. See https://stripe.com/docs/marketplaces for documentation.'
```

**Comment by brunogaspar** [comment]
Seems to be something that you'll need to bring up with Stripe itself i guess.

**Comment by brunogaspar** [comment]
Just reference them the message they return

> Transfers to Recipient objects are not supported in your country (CA); try transferring to another Stripe account instead. See https://stripe.com/docs/marketplaces for documentation.

**Comment by monove** [comment]
needed to be `recipient: "self"`

**Comment by brunogaspar** [comment]
Interesting, that's not documented, right?

**Comment by monove** [comment]
As usual

**Comment by brunogaspar** [comment]
Heh, it's hard to have everything documented.

You want to raise an "issue" on their [Google group](https://groups.google.com/a/lists.stripe.com/forum/#!forum/api-discuss)? They usually reply and the documented get's updated.
