### ISSUE TITLE
100x charge for zero-decimal currencies

### ISSUE THREAD

**Issue by Casinelli** [cartalyst/stripe#59]
There's a few currencies with no decimals. For these Stripe doesn't require to specify the cents, so multiplying the number by 100 actually increases the charge by 100. [Docs here.](https://support.stripe.com/questions/which-zero-decimal-currencies-does-stripe-support)

**Comment by brunogaspar** [comment]
@Casinelli Can you elaborate on the issue? Are you saying that something is broken on our code?

I know that our converter is not really the best thing, which will be removed on the next major version, but i'm not really following your issue.

**Comment by Casinelli** [comment]
@brunogaspar Basically with the package I can send a 50 euros charge by just using 50 as the amount, which the code will convert in 5,000 euro cents. This is good. But if I want to send 2,000 JPY (japanese yen), a currency that doesn't have decimals, the code will now convert it into 200,000. However Stripe doesn't expect the amount to be in cents for zero-decimal currencies, so the customer will get a hundred times higher charge.

I just charged someone the equivalent of 6000 dollars instead of 60 :)

So I think the code should check if the currency is one of the zero-decimal, and convert the amount in cents only if it's not one of them.

**Comment by brunogaspar** [comment]
Feel free to submit a PR if you have a good solution :)
