### ISSUE TITLE
Idempotent key length is 0, which is outside accepted lengths

### ISSUE THREAD

**Issue by KHMtravel** [cartalyst/stripe#65]
On my live server, when I'm trying to create a customer I receive the following error:

> Idempotent key length is 0, which is outside accepted lengths. Idempotent Keys must be 1-255 characters long. If you're looking for a decent generator, try using a UUID defined by IETF RFC 4122.

I'm not trying to set an idempotency key. However if I try to set an idempotency key I receive the same error message.

I'm using 
cartalyst/stripe                      v2.0.5 
cartalyst/stripe-laravel              v4.0.1

This is my code
`\Stripe::customers()->create([
                                            'source' => $request->get('stripeToken'),
                                            'email' => $user->email);`

Same code works on my development machine with the same version of composer packages.

**Comment by brunogaspar** [comment]
I'm not being able to reproduce the issue with the code you've provided.

If you figure out a way to fix it, feel free to submit a PR.

**Comment by KHMtravel** [comment]
Strange thing is that the exact same code works on my development machine.
Is there a way to send header values with the request?

**Comment by brunogaspar** [comment]
> Is there a way to send header values with the request?

Not by default, you'll need to kinda extend the package, but you don't really need to send any extra headers to Stripe.

What PHP version are you using on your production server?

**Comment by KHMtravel** [comment]
output of php -v on my server:
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )

on my laptop:
PHP 7.0.9-1+deb.sury.org~xenial+1 (cli) ( NTS )

Does calling \Stripe::idempotent(NULL) has any effect on the headers sent?

**Comment by brunogaspar** [comment]
> Does calling \Stripe::idempotent(NULL) has any effect on the headers sent?

Can you give that a try please?

If that fixes the issue we can try to set it as `null` [here](https://github.com/cartalyst/stripe/blob/2.0/src/Config.php#L51) otherwise a change will need to happen [here](https://github.com/cartalyst/stripe/blob/2.0/src/Api/Api.php#L188-L193).

**Comment by KHMtravel** [comment]
Doesnt work either.
Also if I set Idempodency-Key to null, I receive the same error message.
If I remove line 190 completely it works.
It seems like null is translated to an empty string somewhere.

I think the best solution for me is to actually use idempotency keys with \Stripe::idempotent(uniqid())

**Comment by brunogaspar** [comment]
That's a very weird error since it works on your dev environment and on my end as well, which leads to something on your production environment to work differently.

---

What about changing [this](https://github.com/cartalyst/stripe/blob/2.0/src/Api/Api.php#L185-L194) with the following

```php
$stack->push(Middleware::mapRequest(function (RequestInterface $request) {
    $config = $this->config;

    if ($idempotencykey = $config->getIdempotencyKey()) {
        $request = $request->withHeader('Idempotency-Key', $idempotencykey);
    }

    $request = $request->withHeader('Stripe-Version', $config->getApiVersion());

    $request = $request->withHeader('User-Agent', 'Cartalyst-Stripe/'.$config->getVersion());

    $request = $request->withHeader('Authorization', 'Basic '.base64_encode($config->getApiKey()));

    return $request;
}));
```

**Comment by KHMtravel** [comment]
sounds good!
I'm gonna test it later and let you know.

**Comment by KHMtravel** [comment]
works like a charme.
Thank you!

**Comment by brunogaspar** [comment]
Thanks for checking it out, i'll push this as a fix on monday.
