### ISSUE TITLE
[Proposal] Integration of Stripe with Cygnite Framework

### ISSUE THREAD

**Issue by sanjoydesk** [cartalyst/stripe#66]
I would like to send you PR for integrating Stripe with Cygnite. I have [created a branch](https://github.com/cygnite/stripe) and wish to provide a section for Stripe in [Cygnite documentation ](http://www.cygniteframework.com/2013/07/introduction.html).  Also it will be nice if we can see [here](https://cartalyst.com/manual/stripe/1.0#integrations).
Thanks!

**Comment by brunogaspar** [comment]
Thanks for the proposal, but this is a framework agnostic package, so it's better if you release your implementation as a standalone package instead, like how we do for Laravel.

After that we can just make a link to your implementation on the documentation.
