### ISSUE TITLE
USD getting converted from cents to dollars in Utility class

### ISSUE THREAD

**Issue by alexrayan** [cartalyst/stripe#67]
Working on a Stripe payment integration in several projects and it looks like the amount passed to Charges class POST processing is being converted from cents to dollars in case of currency being USD. 
Upon further search, I noticed that Utility has an array of currencies to be excluded from conversion within the needsAmountConversion() method. However, USD is not in that array. 
`

    {
        $hasCurrency = isset($parameters['currency']);
        $currencies = [
            'BIF', 'DJF', 'JPY', 'KRW', 'PYG',
            'VND', 'XAF', 'XPF', 'CLP', 'GNF',
            'KMF', 'MGA', 'RWF', 'VUV', 'XOF',
        ];

        return ! $hasCurrency || ($hasCurrency && ! in_array($parameters['currency'], $currencies));
    }
`

Is this something intentional? How would cents be sent for processing then? 

If I want to send $0.50, shouldn't it be 50 for amount value? Amount field expects an integer (_"A positive integer in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge ¥100, a 0-decimal currency) representing how much to charge the card. The minimum amount is $0.50 US or equivalent in charge currency."_). 
As of now, I added USD to the array of $currencies, but I'd appreciate any feedback on this.

**Comment by brunogaspar** [comment]
For now just pass `0.50`, you can see examples of it [here](https://github.com/cartalyst/stripe/blob/2.0/tests/AmountConverterTest.php).

What i can do for the current release though, is to allow the amount converter to be disabled, by allowing you to do `Stripe::disableAmountConverter();`.

But i'm planning on removing the amount converter on the next major release.

**Comment by alexrayan** [comment]
Ok, thanks, Bruno!

We're using cents as the lowest currency denomination within our applications, so for now Stripe::disableAmountConverter() would work well for our needs. 

Thanks for the heads up on the next major release. 

Regards. 
Alex

**Comment by brunogaspar** [comment]
Will keep this open until i add that method in so i don't forget.
