### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by andreipan** [cartalyst/stripe#69]
Plans parameters **statement_descriptor** should be used instead of **statement_description**

https://stripe.com/docs/api/php#plans
https://cartalyst.com/manual/stripe/2.0#plans

**Comment by brunogaspar** [comment]
Feel free to submit a [pull request](https://help.github.com/articles/using-pull-requests/) :)

**Comment by andreipan** [comment]
It's seems like I don't have permissions to do so.

**Comment by brunogaspar** [comment]
Fork the repository, apply the changes there and submit the pull request here.

**Comment by andreipan** [comment]
Somehow I couldn't fork a repo through Fork button. Getting following error:

> You already have a fork of this repository:
>     cartalyst/stripe
> You don’t have permission to fork to these organizations:
>    cartalyst

I've cloned it just by url.
And I guess I can't send topic brunch directly here.

**Comment by brunogaspar** [comment]
You already have a fork as you can see here https://github.com/andreipan/stripe so do the change there.

**Comment by andreipan** [comment]
Already done there, but I can't find the way to create a pull request to cartalyst/stripe. Somehow there is no my repo in "compare across forks" if to do it through cartalyst/stripe and there is no  cartalyst/stripe repo if to do it from my fork.

**Comment by brunogaspar** [comment]
I see why... you don't have a fork, you've created the repository called `stripe` and pushed the changes to that repository, therefore you cant' do a pull request here from your repository, which is expected hehe

So my suggestion is, delete the repository you have and create a proper fork of this repository to your profile, apply the changes for the documentation and you can then submit a pull request here.

You can also read the GitHub documentation on how to proper do this, it's an opportunity to learn something today :)

**Comment by andreipan** [comment]
#71 
Finally figure out the way to do it.

**Comment by brunogaspar** [comment]
Awesome :)
