### ISSUE TITLE
Failed Charge::create() identifier not passed to Exception

### ISSUE THREAD

**Issue by alexrayan** [cartalyst/stripe#70]
Hi!
Is there a possibility of passing a charge identifier to a CardErrorException object? 

As it is now, a failed response returns a charge identifier as part of error array but is not being passed to an exception by the package. 
Here's a logged body of the response: 
`
    [
      "error" => [
        "message" => "Your card was declined."
        "type" => "card_error"
        "code" => "card_declined"
        "charge" => "ch_18wLSEFL3W3Xf0ocVrORvj1iu"
      ]
    ]
`

I suppose it could be a fairly common scenario when an application would like to internally record a failed charge as well (since it gets created within Stripe) for the logging purposes. 

I was looking into Stripe documentation regarding the Error response and it doesn't mention any additional parameters besides type, message, code, and param. But it does, in fact, return "charge" as part of failed charge response. 

I'm planning on adding this to my cloned package, but wondering if this is something that can be added in the future release of this master package as well? 

Best regards, 
Alex

**Comment by brunogaspar** [comment]
Feel free to submit a [pull request](https://help.github.com/articles/using-pull-requests/) :)

**Comment by alexrayan** [comment]
Submitted a pull request :)
