### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by Jkurbs** [cartalyst/stripe#76]
Hi, do you have any guide on how to use the library? Thanks!!

**Comment by brunogaspar** [comment]
The documentation already has a lot of examples, what else do you need?

Anything you're stuck with?

**Comment by Jkurbs** [comment]
Hi, my problem is, I'm building an app and the App rent stuff. So should I use Stripe subscription for creating a plan for every product? What should I use? Thanks

Sent from my iPhone

On Dec 10, 2016, at 3:05 PM, Bruno Gaspar <notifications@github.com<mailto:notifications@github.com>> wrote:


The documentation already has a lot of examples, what else do you need?

Anything you're stuck with?

-

**Comment by brunogaspar** [comment]
If your application requires a recurring billing system, which would happen every month or every couple months for example, the subscriptions is the best option, otherwise use normal charges.
