### ISSUE TITLE
Refunds

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#77]
The stripe API supports using refunds without knowing their charge ID, but cartalyst does not. This makes it impossible to lookup the charge ID if we only know the refund ID, for example.

**Comment by GrahamCampbell** [comment]
Infact, the stripe does don't even mention the endpoints listed in your stripe package. Did they ever work?

**Comment by brunogaspar** [comment]
@GrahamCampbell This should be fixed on the `master` (v3) branch.

But answering:
> Infact, the stripe does don't even mention the endpoints listed in your stripe package. Did they ever work?

It works fine for older accounts as the tests were passing perfectly fine, however for new Stripe accounts, Stripe doesn't allow the old endpoints to work, seems weird but it's how they role i suppose.
