### ISSUE TITLE
Create token method accept only one parameter - no opts

### ISSUE THREAD

**Issue by zlorkovic** [cartalyst/stripe#80]
On original Stripe API, create token method accepts additional parameters. 

https://stripe.com/docs/api#token_object

This is useful when we're using "Sharing customers" feature where create token should accepts two arrays (one is for user who is paying and another is user who is receiving payment)

https://stripe.com/docs/connect/shared-customers

\Stripe\Token::create(
  array("customer" => CUSTOMER_ID, "card" => CARD_ID),
  array("stripe_account" => CONNECTED_STRIPE_ACCOUNT_ID) // id of the connected account
);

This is really issue for our platform as we can't charge connected accounts with this library :(

**Comment by brunogaspar** [comment]
@zlorkovic Please have a read on our [documentation](https://cartalyst.com/manual/stripe/2.0#tokens), it accepts an array as the first argument, so you can pass whatever the Stripe API accepts.

Let me know if you have any issues with it.

**Comment by zlorkovic** [comment]
@brunogaspar Couldn't make it work. It accepts array (one argument) but in their documentation (code I posted above) it should accept two arguments. Both of them are arrays.
I've try to add both of them in additional array but without success as it doesn't accept it that way.

**Comment by brunogaspar** [comment]
@zlorkovic The code on your example is for the Official Stripe PHP library, if it doesn't work, then you should use their own [repository](https://github.com/stripe/stripe-php) and report the problem there.

Our Stripe Library only accepts one argument and it does work, so you're probably confused on the library you're using.

**Comment by zlorkovic** [comment]
@brunogaspar It's working on official library. I just thought that this Stripe Library is like "wrapper" for official stripe library. 
Sorry for confusion. I've realised now that it's completely separated library.
Just one quick question, do you support managed accounts or this is in plan for future versions?

**Comment by brunogaspar** [comment]
> Sorry for confusion. I've realised now that it's completely separated library.

No problem :)

> Just one quick question, do you support managed accounts or this is in plan for future versions?

Yes, it's supported.

**Comment by zlorkovic** [comment]
@brunogaspar Great! Have one more question, so I don't open new issue in vain. 
Is requesting that Tokens method can receive additional, optional argument, valid feature request or?
Because, when using managed/connected accounts, this is pretty big issue as I need to generate token using user info, and managed/connected user info, both need to be provided as arrays to token endpoint (as I mention from official stripe php library).

**Comment by brunogaspar** [comment]
Don't believe that's necessary, one argument is enough, but what are you trying to pass to the tokens endpoint?

**Comment by zlorkovic** [comment]
I'm trying to pass customer_id (I have that info saved in local database, while on info about customer is saved in one Stripe account - cc, bank details etc) - user who is paying, and user_stripe_id of connected account - user who should received founds.
Then when I get this token, I can make charge.

I need to pass two arguments to token because all customers info are saved on one account (our stripe account - as platform) and not on connected account. So to get token for charge, beside customer_id (customer object) I also need to pass stripe_id of connected user.

Don't know does this make sense?

**Comment by brunogaspar** [comment]
I think what you're after is the way to tell Stripe which connected account to use.

We've a method called `accountId()` that set's that, but this is not on a stable release though, but i can create a tag for it later tonight, otherwise you'll need to set your composer.json file allow dev dependencies but updating the minimum stability flag to `"minimum-stability": "dev"`

In terms of usage is quite simple.

First you need to tell our library which connected account to use using: `$stripe->accountId($connectedAccountId);`

After this you can perform any call, for example:

```php
$account = $stripe->account()->create([
    'email' => 'john@doe.com',
    'managed' => true,
]);
```

The same principle applies on tokens as well.

Hopefully it helps.

**Comment by zlorkovic** [comment]
Oh. I see. Yeah, that could work I think.

**Comment by zlorkovic** [comment]
@brunogaspar If you don't mind create a tag for it so I'll try to pull it later to check if it will work that way.

**Comment by brunogaspar** [comment]
@zlorkovic Tagged. Please give a try and let me know if it works as how you expect.

**Comment by zlorkovic** [comment]
@brunogaspar Yes, it's working as expected. Thank you!
