### ISSUE TITLE
Implement Multiple Plans per Subscription

### ISSUE THREAD

**Issue by brunogaspar** [cartalyst/stripe#81]
Refs:
- https://stripe.com/docs/subscriptions/multiplan
- https://stripe.com/docs/api#subscription_items

**Comment by edmundluong** [comment]
Hey guys,

I was looking for specific functionality of adding multiple plans to a subscription and was going to create an issue here but I found this ticket and it seems like its already been implemented. The documentation, however, does not reflect this.

I can get by looking at the source code, but it would be nice if this was in the docs as well.

Thanks and keep up the great work!
