### ISSUE TITLE
[Proposal] - Pass extra parameters when retrieving an upcoming invoice

### ISSUE THREAD

**Issue by rnatmigl** [cartalyst/stripe#82]
The upcoming invoice method on Stripe accepts several parameters.

https://stripe.com/docs/api#upcoming_invoice

It allows us to preview the next invoice amount if a user wants to update his subscription or use a coupon, for example.

Unfortunately Cartalyst only accepts the $customerId and $subscriptionId parameters:
`upcomingInvoice($customerId, $subscriptionId = null)`

Would be good to have it accepting an array of parameters so we can pass anything that Stripe allows.

**Comment by brunogaspar** [comment]
Will make this change for the upcoming v3, doing it now on v2 would be a breaking change.

**Comment by rnatmigl** [comment]
Great.
Thanks for the quick reply.

**Comment by brunogaspar** [comment]
I've implemented this on the `master` branch.
