### ISSUE TITLE
"Stripe-Account" Causing Error when not using Connect

### ISSUE THREAD

**Issue by brentnd** [cartalyst/stripe#84]
I'm using v2.0.8 as I have on previous projects. This time however, I'm not using Stripe connect and I'm running into an issue making a simple charge.

The error returned is ```Only Stripe Connect platforms can work with other accounts. If you specified a client_id parameter, make sure it's correct. If you need to setup a Stripe Connect platform, you can do so at https://dashboard.stripe.com/account/applications/settings.```

The culprit for me seems to be `$request = $request->withHeader('Stripe-Account', $config->getAccountId());`, because when I remove it, the charge goes through. I'm not ever setting the accountId because I'm not using Stripe connect.

Any thoughts on why this would be not working now? I'm using Stripe API version 2017-02-14 (latest).

**Comment by brunogaspar** [comment]
Hello @brentnd 

Can you see if the following change on the `createHandler` method on the `src/Api/Api.php` file works?

```php
protected function createHandler()
{
    $stack = HandlerStack::create();

    $stack->push(Middleware::mapRequest(function (RequestInterface $request) {
        $config = $this->config;

        if ($idempotencykey = $config->getIdempotencyKey()) {
            $request = $request->withHeader('Idempotency-Key', $idempotencykey);
        }

        if ($accountId = $config->getAccountId()) {
            $request = $request->withHeader('Stripe-Account', $accountId);
        }

        $request = $request->withHeader('Stripe-Version', $config->getApiVersion());

        $request = $request->withHeader('User-Agent', 'Cartalyst-Stripe/'.$config->getVersion());

        $request = $request->withHeader('Authorization', 'Basic '.base64_encode($config->getApiKey()));

        return $request;
    }));

    $stack->push(Middleware::retry(function ($retries, RequestInterface $request, ResponseInterface $response = null, TransferException $exception = null) {
        return $retries < 3 && ($exception instanceof ConnectException || ($response && $response->getStatusCode() >= 500));
    }, function ($retries) {
        return (int) pow(2, $retries) * 1000;
    }));

    return $stack;
}
```

> Basically just set the header if the account id is set.

The weird thing is that the tests are passing just fine and i don't have any issues on 2 productions servers either, but the above change should fix it.

**Comment by brentnd** [comment]
Yes, adding the condition like idempotencyKey solves it as well.

I too am confused though, because I've had this working before on other accounts without needing this change. Could it be that a newly created account is somehow different? One difference is I'm using Stripe elements on the front end but to me, the way the token is generated shouldn't change how the backend handles it.
