### ISSUE TITLE
Support for a "direct charge"?

### ISSUE THREAD

**Issue by johndwells** [cartalyst/stripe#85]
We need to raise a "direct charge" with Stripe Connect:

https://stripe.com/docs/connect/direct-charges

The curl example shows sending `Stripe-Account` as a header value.  I'm not seeing any evidence of being able to do this here.

Are "direct" charges possible?

**Comment by brunogaspar** [comment]
Hello @johndwells 

Yes, this is possible but not documented as of yet.
I plan on revising the documentation soon, so it gets inline with out Stripe has their documentation now.

Just do something:

```php
Stripe::accountId('the-connected-account-id-here')->charges()->create([ .. ])
```

Let me know if you find any issues with it.

**Comment by johndwells** [comment]
Thank you for the prompt reply! That's super helpful we'll forge on with this and let you know if we encounter trouble.
