### ISSUE TITLE
Update Customers Default Card

### ISSUE THREAD

**Issue by jberm4** [cartalyst/stripe#86]
I am trying to update a customers default_source to the new card that is added to their account. Is there a way to do this? The below does not work.

$customer = $stripe->customers()->update($user->stripe_id, [
      'default_source' => $card[id]
    ]);

**Comment by brunogaspar** [comment]
Hello @jberm4 

This seems to be working as expected, i even added a test [here](https://github.com/cartalyst/stripe/commit/fc1413da0aabc4852e574ca21d4f8b8801297fab) to make sure it is really working.

Is it returning any error? What does the `$card['id']` contain?

**Comment by jberm4** [comment]
As you can see I had a typo in $card[id]. I figured out my issue. I apologize. Long hours of coding.
