### ISSUE TITLE
Library security question

### ISSUE THREAD

**Issue by eduardoconekta** [cartalyst/stripe#89]
How you manage api header security to avoid header parameters interception by server side?.
 I found in Api.php this is a plain text `createHeader()` function that let me see that you only need 

- Idempotency-Key
- Stripe-Account
- Stripe-Version
- Authorization', 'Basic '.base64_encode($config->getApiKey()));

to auth into your api, what appends if some one compromise the traffic between the server and your api , actually he could see that information and access to company information.

**Comment by brunogaspar** [comment]
Hello @eduardoconekta 

I'm not seeing how this can be avoided at a package level to be honest, but i'm not by any means a security expert so i can be totally wrong.

If you have something to improve in this regard, please feel free to submit a PR or just leave a comment here.

Thanks!

**Comment by eduardoconekta** [comment]
I'm talking to put a proxy between server traffic, spoofing all the requests made by server including api calls, every api call may contain *headers*, that means an attacker could steal those, put in i don't know may be postman or a curl petition to get access to all information

**Comment by drsii** [comment]
@eduardoconekta this type of attack cannot be resolved by the package itself.  

Adding a proxy between your server for obfuscation comes with it's own set of problems and would fall to the project lead that is designing the hardware/tech stack for the given project.

Your best option is to run your entire app in https.

**Comment by eduardoconekta** [comment]
i think i wasn't clear, please read again my last comment i restructured the case, so here in México there was an issue with a startup that make api calls over android app and a guy use a program called mitmproxy was able to download the entire database, even when the traffic was over https, so i think that could be a posible security issue if you know how headers work.
Here is a post with a similar usage of <a href="https://blog.heckel.xyz/2013/07/01/how-to-use-mitmproxy-to-read-and-modify-https-traffic-of-your-phone/ " >mitmproxy</a> with https

**Comment by drsii** [comment]
@eduardoconekta I see. I'm not sure there is much we can do here. I would tend to shy away from obfuscation for security but in this case it could make sense. I'm still not sure this is something i would like to see on any of our packages.

I'll take some time to research any other use cases out there. Feel free to share anything you learn as well.
