### ISSUE TITLE
Payout file is missing in latest release.

### ISSUE THREAD

**Issue by arslan-lango** [cartalyst/stripe#90]
I am using your latest release 2.0.9 but that release does not include the payout file. kidnly upload the latest release that has the payout work.

**Comment by GrahamCampbell** [comment]
Or you could just set the correct stability so that you can use the new code.

**Comment by brunogaspar** [comment]
@arslan-lango As @GrahamCampbell mentioned, and if you can't wait (which is understandable), you can update your `minimum-stability` to `dev` on your `composer.json` file and require the `2.0.x-dev` version for now.

I'll try to address the tag ASAP as i need to create the unit tests for it before creating the new release.

Thanks @GrahamCampbell

**Comment by arslan-lango** [comment]
Thanks @GrahamCampbell and @brunogaspar

**Comment by brunogaspar** [comment]
It's tagged @arslan-lango.
