### ISSUE TITLE
Handle token() Error

### ISSUE THREAD

**Issue by WeeHong** [cartalyst/stripe#92]
Hi,

Could I know how to handle the error when `$this->token()->create([ ... ])` is running?

It never goes into `catch Exception`.
```
try {
    $token = $stripe->tokens()->create([
        'card' => [
            'number' => $request->card,
            'exp_month' => $request->month,
            'exp_year' => $request->year,
            'cvc' => $request->cvc
        ]
    ]);
} catch (
    catch (Cartalyst\Stripe\Exception\CardErrorException $error) {
        dd($error);
    }
}
```

**Comment by brunogaspar** [comment]
This seems to be a namespace issue.

Either try importing the `Cartalyst\Stripe\Exception\CardErrorException` exception class at the beginning of your file, or prepend a `\` at the beginning like so `\Cartalyst\Stripe\Exception\CardErrorException`.

Please have a read on namespaces on the PHP documentation, it explains it very well how this kind of stuff work.

**Comment by EduardoAlliance** [comment]
never catch expection

try{
                    $charge = $stripe->charges()->create([                  
                        'amount' => '1',
                        'currency' => 'USD',
                        'description' => 'Order '.$order->invoice_id,
                        'customer' => $user->customer_stripe
                    ]);
                    if($charge['status'] == 'succeeded'){
                     
                    }

                }catch(\Cartalyst\Stripe\Exception\CardErrorException $error ){
                    dd($error);
                }

error
local.ERROR: Your card does not support this type of purchase. {"userId":31,"exception":"[object] (Cartalyst\\Stripe\\Exception\\CardErrorException(code: 402): Your card does not support this type of purchase. at /home/l21rentals/latitude_app/vendor/cartalyst/stripe/src/Exception/Handler.php:123)
