### ISSUE TITLE
Autogenerate idempotency keys for requests

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#93]
Instead of allowing a user to set a global idempotency key, instead, would it not be a better idea to just automatically set a random one for each request, to ensure the request retrying middleware doesn't do anything bad?

**Comment by brunogaspar** [comment]
Having it to send the idempotency key header on **all** requests or just when the idempotency method is called?

**Comment by GrahamCampbell** [comment]
> Having it to send the idempotency key header on all requests or just when the idempotency method is called?

**Comment by GrahamCampbell** [comment]
> Having it to send the idempotency key header on all requests

Doing that is a very bad idea, and won't work properly. I am proposing the current idempotency stuff is retained, but if it's not specified, then we should randomly generate one for the current request, so that the retry middleware behaves well.

**Comment by GrahamCampbell** [comment]
> Doing that is a very bad idea

By that, I mean, sending the same key with every request. Hopefully it's clearer what I meant from the previous comment.

**Comment by brunogaspar** [comment]
> Doing that is a very bad idea, and won't work properly.

Yap, was just wondering what you were proposing, as the proposal was very vague.

> By that, I mean, sending the same key with every request. Hopefully it's clearer what I meant from the previous comment.

I think i'm ok with that.

**Comment by brunogaspar** [comment]
@GrahamCampbell Are you planning on sending a PR for this?
