### ISSUE TITLE
Capture a Charge

### ISSUE THREAD

**Issue by kezern** [cartalyst/stripe#95]
I have craeted a charge with this code.
	       `$charge = $stripe->accountId('acct_XXXXXXXXX')->charges()->create([
	            'currency' => 'EUR',
	            'amount'   => $cobro->importe,
	            'source' => $token['id'],
	            'description' => $cobro->descripcion,
	            "application_fee" => $application_fee,
	        ]);`
When I try to capture it with 

`$capture= $stripe->accountId('acct_XXXXXXXX')->charges()->capture('ch_XXXXX');`
I get a message about the charge is already captured.
In the documentation in this [https://cartalyst.com/manual/stripe/2.0#charges](https://cartalyst.com/manual/stripe/2.0#charges) appears capture as a non required parameter and its default value as null.
Is it necessary to caputre a charge?

Regards!

**Comment by brunogaspar** [comment]
You'll need to pass capture as false when creating the charge, otherwise Stripe will automatically capture the charge.

**Comment by kezern** [comment]
Thank you.
I don't understand the benefits of not capturing charges.

**Comment by brunogaspar** [comment]
> I don't understand the benefits of not capturing charges.

It depends on the flow your application requires.

Usually the not capture automatically can be seen for example on Amazon, where they only charge when they are ready to fulfil the order. Another scenario is on pre orders.

But for most of the applications, capturing the charge right away is more than enough.
