### ISSUE TITLE
[Proposal] Add support for multiple plans per subscription

### ISSUE THREAD

**Issue by quietseditionist** [cartalyst/stripe#96]
The Stripe API calls this feature 'multiplan' or 'subscription items'.

https://stripe.com/docs/subscriptions/multiplan

You could potentially leave the plan parameter on the subscription requests (change to optional?), but also include an optional argument to hold an array of plans.

**Comment by brunogaspar** [comment]
Hello @quietseditionist 

This is already possible, i was thinking on something else when i replied to your ticket, sorry.

Documentation wise, that's correct, it's not there, which is something that i'm already working on the `feature/docs-refactor` branch.

How to use, nothing complicated, just pass an array of items that contains the plans, something like this:

```php
Stripe::subscriptions()->create('cus_123', [
    'items' => [
        ['plan' => 'my-plan-id-here'],
        ['plan' => 'my-other-plan-id-here'],
    ],
]);
```

The same applies for updating.

However, we also have the [Subscription Items](https://stripe.com/docs/api/php#subscription_items) implemented too.

Which allows to manage those items for a subscription:

```php
Stripe::subscriptionItems()->create('sub_123', 'my-plan-id-here');
```

Let me know if something doesn't work.
