### ISSUE TITLE
Stripe Connect Accounts

### ISSUE THREAD

**Issue by riteshkhatri** [cartalyst/stripe#97]
Hello, 
I had used thid plugin and i have requirement to connect account though the platform,
I Had connected accounts through
$stripe->account()->create();
The account is created inside the platform and everything is working perfect.
But my question is how the connected account user know that his/ her account is created and they need to fill up their bank account detail for further payout.
Is stripe send some mail to know user that his / her account is created and provide their email and temp password? I checked through test keys mail is not going.
I realy stucked in this please help me out.
sorry for my bad english, Any help will be appreciated.

**Comment by brunogaspar** [comment]
Hello,

Stripe sends an email with instructions for new accounts.

If you're still confused it's better to read their documentation or contact Stripe directly for more information about connected accounts.

Hope it helps.

**Comment by riteshkhatri** [comment]
The doc does not mention what you said, any ways thanks it really appreciated.
I tried in test mode but connected account does not get any mail, is it possible in only Live mode??

**Comment by brunogaspar** [comment]
> The doc does not mention what you said, any ways thanks it really appreciated.

It's kinda mentioned [here](https://stripe.com/docs/api#create_account-email).

> I tried in test mode but connected account does not get any mail, is it possible in only Live mode??

Probably better to ask this directly to Stripe :)

**Comment by riteshkhatri** [comment]
Thanks, Thank you so much...:)
