### ISSUE TITLE
Adding metadata to a token created card

### ISSUE THREAD

**Issue by eaarranz** [cartalyst/stripe#98]
Hi! We are using your integration to handle the payments on our platform. In order to create the cards, we are using tokens:
`$card = Stripe::cards()->create($customer_id, $token);`
We also want to add metadata to the card since Stripe allows it. And we are unable to find a clean way to do that with your implementation.
We are solving the issue updating the card after the creation, with that we are adding the metadata to the card, and it's working, but it's not the best way:
`$card = Stripe::cards()->update($customer_id, $card['id'], ['metadata' => ['cif' => $data['cif']]]);`
Do you have a better way to do it?
Also, you can add 'metadata' as a param to the card()->update() method on your documentation, it's working just fine. 
Thx! :)

**Comment by brunogaspar** [comment]
Hello @eaarranz 

Yeah, this is an issue with the `create` method. I'll have a look and see if i can make it work without causing a breaking change on this release. I've done a few changes for v3 locally and this was actually one of them, but nothing is pushed nor production ready at the moment.

> Also, you can add 'metadata' as a param to the card()->update() method on your documentation, it's working just fine.

Ya, documentation is being "reworked" at the moment, so that should be covered :)

I'll let you know either way if i figure out a good way to handle this the proper way.

Cheers!

**Comment by eaarranz** [comment]
Thx! 👍

**Comment by brunogaspar** [comment]
Hello @eaarranz 

I've pushed a fix for this, but if you pass a token, you'll need to pass an array with the source as key and the token as the value (check example below).

I'll make this a bit better on version 3, as for now, i don't want to maybe cause a breaking change.

Example:

```php
Stripe::cards()->create($customer_id, [
    'source' => $token,
    'metadata' => [
        'foo' => 'bar',
    ],
]);
```

The way i plan to make it work on v3 is by having a 3rd parameter for the parameters and the 2nd for the card data or token.
But i'll have to think about it when i restart working on it :)

Do let me know if it still doesn't work as expected and i'll have another look at it.

**Comment by eaarranz** [comment]
Hi @brunogaspar!
Thanks, that looks good :+1: , i'll try to use it next week and I'll tell you if it's working.
