### ISSUE TITLE
Creating a source requires a customer

### ISSUE THREAD

**Issue by adamcmoore** [cartalyst/stripe#99]
To implement 3D secure a source must be created: https://stripe.com/docs/sources/three-d-secure#server-side-source-creation

A customer is not required by Stripe for the source creation but the Cartalyst API requires a customer_id to use the Sources method.

Am I missing something here?

**Comment by brunogaspar** [comment]
Hello @adamcmoore,

That is entirely correct!

At the moment our code has the implementation on how Stripe used to have sources.

I've started to update this on a separate [feature/improve-sources-endpoint](https://github.com/cartalyst/stripe/tree/feature/improve-sources-endpoint) branch, but to lack of time, haven't had the time to fully finalise it & ensure tests pass etc.. yet.

You're free to use that branch if you want, but keep in mind that we're not responsible if it's not working as expected.

I can't give any ETA but i can try to make it merged into the 2.0 branch and maybe tagged this week or earlier next week, if i can hopefully find some spare time to properly look at this.

Hope you understand 😉

**Comment by adamcmoore** [comment]
Thanks for the quick response, and the honesty @brunogaspar!

I'll use the feature branch for the time being - the other changes in the branch won't affect my application, so willing to use untested for the short term.

Cheers :+1:

**Comment by brunogaspar** [comment]
Hello @adamcmoore 

This is now on the `2.0` branch, will push some tests and a tag on the upcoming days.

Will keep the feature branch until this is tagged though.

Thanks!
